### ISSUE TITLE
admins cannot go into staff channel

### ISSUE THREAD

**Issue by nkidwell1259** [TomGrobbe/vMenu#101]
Staff channel does not show up for any admins in the voice channel section

**Comment by TomGrobbe** [comment]
@nkidwell1259 Are you sure you setup the permissions correctly? (Did you give permissions to the staff channel to moderators or to admins?)

**Comment by nkidwell1259** [comment]
I didnt see where that needed to be changed. I thought it was set up that
admins and moderators once added as admins or moderators would have access.

**Comment by TomGrobbe** [comment]
@nkidwell1259 You need to add yourself as a moderator *and* admin, because group inheritance does not work.

**Comment by nkidwell1259** [comment]
I did. I added 6 of us as admin and moderators via instructions and can use
admin features. But staff doesnt show up in the channels. Just 1-4

**Comment by TomGrobbe** [comment]
Code hasn't changed, and it has always worked perfectly fine:
https://www.vespura.com/hi/i/4c995dfabd.png
so it's probably a permissions error when you configured it.

**Comment by nkidwell1259** [comment]
I added our steam ids to the admin list. No changes were made for the
allowed denied in the permission.cfg

**Comment by TomGrobbe** [comment]
@nkidwell1259 Can you show me the permissions.cfg?

**Comment by nkidwell1259** [comment]
``#############################################################################################
# This is the default permissions file used by vMenu.                                       #
# Example groups include: moderator, admin                                                  #
# You can add your own groups or use the example groups and add players to those groups     #
# The add permissions to "builtin.everyone" to allow anyone to use those features.          #
#																							#
# FOR A LIST OF ALL PERMISSIONS, CHECK https://github.com/TomGrobbe/vMenu/wiki/permissions  #
#############################################################################################




######## Add players to groups ########
# Admin group players:
add_principal identifier.steam:11000011d052f08 group.admin
add_principal identifier.steam:11000011c3c93cc group.admin
add_principal identifier.steam:110000106e59eae group.admin
add_principal identifier.steam:110000131f97c30 group.admin
add_principal identifier.steam:11000011b5e59db group.admin
add_principal identifier.steam:1100001174ad9d3 group.admin
# Moderator group players:
add_principal identifier.license:4510587c13e0b645eb8d24bc104601792277ab98 group.moderator




## NOTE:
# GROUP INHERITANCE IS CURRENTLY BROKEN. TO SOLVE THIS, ADD ALL PLAYERS TO EACH GROUP MANUALLY.
## Setup group inheritance, it's probably best you don't touch this unless you know what you're doing.
#add_principal group.admin group.moderator


## Setup Permissions
# Global Permissions
#add_ace builtin.everyone "vMenu.Everything" allow # (Don't uncomment this, or bad things will happen if you don't know what you're doing.)
# Admins can't be kicked or banned from the server, everyone else can be kicked/banned without mercy though.
add_ace group.admin "vMenu.DontKickMe" allow
add_ace group.admin "vMenu.DontBanMe" allow
# Allow everyone to use noclip by default.
add_ace builtin.everyone "vMenu.NoClip" allow

# Online Players
add_ace builtin.everyone "vMenu.OnlinePlayers.Menu" allow
#add_ace builtin.everyone "vMenu.OnlinePlayers.All" allow
add_ace builtin.everyone "vMenu.OnlinePlayers.Teleport" allow
add_ace builtin.everyone "vMenu.OnlinePlayers.Waypoint" allow
add_ace builtin.everyone "vMenu.OnlinePlayers.Spectate" allow
# only allow moderators + admins to use these:
add_ace group.moderator "vMenu.OnlinePlayers.Summon" allow
add_ace group.moderator "vMenu.OnlinePlayers.Kill" allow
add_ace group.moderator "vMenu.OnlinePlayers.Kick" allow
# moderators can only ban for max 1 month.
add_ace group.admin "vMenu.OnlinePlayers.TempBan" allow
# allow permanent bans for admins only.
add_ace group.admin "vMenu.OnlinePlayers.PermBan" allow
add_ace group.admin "vMenu.OnlinePlayers.Unban" allow

# Player Options
add_ace builtin.everyone "vMenu.PlayerOptions.Menu" allow
add_ace builtin.everyone "vMenu.PlayerOptions.All" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.God" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.Invisible" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.FastRun" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.FastSwim" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.Superjump" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.NoRagdoll" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.NeverWanted" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.SetWanted" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.Ignored" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.Functions" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.Freeze" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.Scenarios" allow

# Vehicle Options
add_ace builtin.everyone "vMenu.VehicleOptions.Menu" allow
add_ace builtin.everyone "vMenu.VehicleOptions.All" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.God" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.SpecialGod" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Repair" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Wash" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Engine" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.ChangePlate" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Mod" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Colors" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Liveries" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Components" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Doors" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Windows" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Freeze" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.TorqueMultiplier" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.PowerMultiplier" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Flip" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Alarm" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.CycleSeats" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.EngineAlwaysOn" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.NoSiren" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.NoHelmet" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Lights" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Delete" allow
#add_ace builtin.everyone "vMenu.VehicleOptions.Underglow" allow

# Vehicle Spawner
add_ace builtin.everyone "vMenu.VehicleSpawner.Menu" allow
add_ace builtin.everyone "vMenu.VehicleSpawner.All" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.DisableReplacePrevious" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.SpawnByName" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Addon" allow # allows you to spawn an addon car from the Addon Vehicles list.
#add_ace builtin.everyone "vMenu.VehicleSpawner.Compacts" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Sedans" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.SUVs" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Coupes" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Muscle" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.SportsClassic" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Sports" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Super" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Motorcycles" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.OffRoad" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Industrial" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Utility" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Vans" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Cycles" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Boats" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Helicopters" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Planes" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Service" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Emergency" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Military" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Commercial" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Trains" allow

# Saved Vehicles
add_ace builtin.everyone "vMenu.SavedVehicles.Menu" allow
add_ace builtin.everyone "vMenu.SavedVehicles.All" allow
#add_ace builtin.everyone "vMenu.SavedVehicles.Spawn" allow

# Player Appearance
add_ace builtin.everyone "vMenu.PlayerAppearance.Menu" allow
add_ace builtin.everyone "vMenu.PlayerAppearance.All" allow
#add_ace builtin.everyone "vMenu.PlayerAppearance.Customize" allow
#add_ace builtin.everyone "vMenu.PlayerAppearance.SpawnSaved" allow
#add_ace builtin.everyone "vMenu.PlayerAppearance.SpawnNew" allow

# Time Options (restricted to moderators & admins only)
add_ace group.moderator "vMenu.TimeOptions.Menu" allow
add_ace group.moderator "vMenu.TimeOptions.All" allow
#add_ace group.moderator "vMenu.TimeOptions.FreezeTime" allow
#add_ace group.moderator "vMenu.TimeOptions.SetTime" allow

# Weather Options (restricted to moderators & admins only)
add_ace group.moderator "vMenu.WeatherOptions.Menu" allow
add_ace group.moderator "vMenu.WeatherOptions.All" allow
#add_ace group.moderator "vMenu.WeatherOptions.Dynamic" allow
#add_ace group.moderator "vMenu.WeatherOptions.Blackout" allow
#add_ace group.moderator "vMenu.WeatherOptions.SetWeather" allow
#add_ace group.moderator "vMenu.WeatherOptions.RemoveClouds" allow
#add_ace group.moderator "vMenu.WeatherOptions.RandomizeClouds" allow

# Weapon Options
add_ace builtin.everyone "vMenu.WeaponOptions.Menu" allow
add_ace builtin.everyone "vMenu.WeaponOptions.All" allow
#add_ace builtin.everyone "vMenu.WeaponOptions.GetAll" allow
#add_ace builtin.everyone "vMenu.WeaponOptions.RemoveAll" allow
#add_ace builtin.everyone "vMenu.WeaponOptions.UnlimitedAmmo" allow
#add_ace builtin.everyone "vMenu.WeaponOptions.NoReload" allow
#add_ace builtin.everyone "vMenu.WeaponOptions.Spawn" allow
#add_ace builtin.everyone "vMenu.WeaponOptions.SetAllAmmo" allow

# add_ace builtin.everyone "vMenu.WeaponOptions.SniperRifle" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.FireExtinguisher" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.CompactGrenadeLauncher" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Snowball" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.VintagePistol" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.CombatPDW" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.HeavySniperMk2" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.HeavySniper" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.SweeperShotgun" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.MicroSMG" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Wrench" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Pistol" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.PumpShotgun" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.APPistol" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Ball" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Molotov" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.SMG" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.StickyBomb" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.PetrolCan" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.StunGun" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.AssaultRifleMk2" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.HeavyShotgun" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Minigun" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.GolfClub" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.FlareGun" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Flare" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.GrenadeLauncherSmoke" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Hammer" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.CombatPistol" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Gusenberg" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.CompactRifle" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.HomingLauncher" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Nightstick" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Railgun" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.SawnOffShotgun" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.SMGMk2" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.BullpupRifle" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Firework" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.CombatMG" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.CarbineRifle" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Crowbar" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Flashlight" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Dagger" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Grenade" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.PoolCue" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Bat" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Pistol50" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Knife" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.MG" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.BullpupShotgun" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.BZGas" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Unarmed" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.GrenadeLauncher" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.NightVision" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Musket" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.ProximityMine" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.AdvancedRifle" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.RPG" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.PipeBomb" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.MiniSMG" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.SNSPistol" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.PistolMk2" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.AssaultRifle" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.SpecialCarbine" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Revolver" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.MarksmanRifle" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.BattleAxe" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.HeavyPistol" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.KnuckleDuster" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.MachinePistol" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.CombatMGMk2" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.MarksmanPistol" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Machete" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.SwitchBlade" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.AssaultShotgun" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.DoubleBarrelShotgun" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.AssaultSMG" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Hatchet" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Bottle" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.CarbineRifleMk2" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.Parachute" allow
# add_ace builtin.everyone "vMenu.WeaponOptions.SmokeGrenade" allow


# Misc Settings
add_ace builtin.everyone "vMenu.MiscSettings.All" allow
#add_ace builtin.everyone "vMenu.MiscSettings.ClearArea" allow
#add_ace builtin.everyone "vMenu.MiscSettings.TeleportToWp" allow
#add_ace builtin.everyone "vMenu.MiscSettings.ShowCoordinates" allow
#add_ace builtin.everyone "vMenu.MiscSettings.ShowLocation" allow
#add_ace builtin.everyone "vMenu.MiscSettings.JoinQuitNotifs" allow
#add_ace builtin.everyone "vMenu.MiscSettings.DeathNotifs" allow
#add_ace builtin.everyone "vMenu.MiscSettings.NightVision" allow
#add_ace builtin.everyone "vMenu.MiscSettings.ThermalVision" allow

# Voice Chat
add_ace builtin.everyone "vMenu.VoiceChat.Menu" allow
#add_ace builtin.everyone "vMenu.VoiceChat.All" allow
add_ace builtin.everyone "vMenu.VoiceChat.Enable" allow
add_ace builtin.everyone "vMenu.VoiceChat.ShowSpeaker" allow

add_ace group.moderator "vMenu.VoiceChat.StaffChannel" allow # Restrict the voice chat staff channel to moderators and admins only

**Comment by TomGrobbe** [comment]
You only added yourself as an admin, not a moderator.....

**Comment by nkidwell1259** [comment]
ok so we have to add to both?

**Comment by TomGrobbe** [comment]
@TomGrobbe Read this ^
