### ISSUE TITLE
vMenu doesnt show up after 1.1.5!

### ISSUE THREAD

**Issue by CaptainPiklas** [TomGrobbe/vMenu#102]
Hey guys, i have a server local hosted and i updated vMenu to 1.1.5 and now i'm pressing "M" to open the menu.. but nothing happens same with noclip "F2" I have these errors in my console could you give me a solution ASAP ? Thanks!
![capture](https://user-images.githubusercontent.com/17181325/41227551-ef623b48-6d7d-11e8-89cc-c5492a26f834.PNG)

**Comment by CaptainPiklas** [comment]
Last night i was adding cars and it was all fine.. but now that happens

**Comment by TomGrobbe** [comment]
@CaptainPiklas Your addons file contains invalid json. According to the error it breaks somewhere in the vehicles section

**Comment by CaptainPiklas** [comment]
What do you suggest me to do ? :D

**Comment by TomGrobbe** [comment]
@CaptainPiklas Either copy the file, and run it through some json verifier online, and look for the mistake. Or, copy the addons file from the fresh download, use that and add your own cars again making sure to avoid any (syntax) errors

**Comment by CaptainPiklas** [comment]
Thanks, I'll try!

**Comment by CaptainPiklas** [comment]
Do you know how i can add more categories and not only the "addon vehicles" ?

**Comment by TomGrobbe** [comment]
@CaptainPiklas Nope, there’s currently no way to do that.
