### ISSUE TITLE
Resource time warning

### ISSUE THREAD

**Issue by AMonk516** [TomGrobbe/vMenu#105]
Hey bud, I'm getting major fps issues when I'm playing on DOJ. At the bottom right it says: vmenu resource time warning -30fps. Would u have a solution for it? :/ I'm sick of playing with 40fps :(

**Comment by TomGrobbe** [comment]
@AMonk516 Which version is the server using?

**Comment by mbergwall2222** [comment]
This is not an issue with vMenu. Contact DOJRP chain of command and don't bug the creator of the resource; ours is a fork, it has many modifications and it is inappropriate to report it here.

**Comment by AMonk516** [comment]
I'm not sure wich version they are using, I am not in the Dev team.
