### ISSUE TITLE
Voice Chat Proximity

### ISSUE THREAD

**Issue by CakeArmy** [TomGrobbe/vMenu#106]
Hi, I might be blind but I don't see where I can either:
Set Default Voice Chat Proximity
Restrict Voice Chat Proximity
Set permissions for different voice chat proximities.

Maybe I am blind? I'm not seeing it as an 'issue' here on the github either. Is this something that isn't yet implemented?

**Comment by TomGrobbe** [comment]
None of this is an option that is currently implemented, and none of them will ever be implemented either. It's all user preference so you can't "override" or force players to use some particular setting. You'll have to use another resource (something like vVoice) if you want a global-synced and permissions based voice system.

**Comment by CakeArmy** [comment]
Okay. If I were to use vVoice, do I just remove the permissions to use the voice chat within vMenu? (Comment it out?)

**Comment by TomGrobbe** [comment]
yes remove all voice chat menu permissions and it'll just disable it.

**Comment by CakeArmy** [comment]
Perfecto, appreciate it :)
