### ISSUE TITLE
Vehicles Handlings

### ISSUE THREAD

**Issue by Yanakis** [TomGrobbe/vMenu#110]
For some reason when the vMenu is running then all the vehicles loses speed/torque, i found out that u can restore the vehicle stats only if u upgrade them again then if someone else sit on the vehicle it lose the stats again.

**Comment by TomGrobbe** [comment]
Are the vehicles modded by vMenu? Or through another resource?

**Comment by Yanakis** [comment]
doesnt matter with which resource are modified,at the moment we modify them with Ls Custom resource but even if we modify them with the vMenu they lose the upgrades or the handlings i dont undestand it at all, every vehicle lose Torque/speed if i run the vMenu.

**Comment by TomGrobbe** [comment]
@Yanakis Does this still happen if you remove the torque/power multiplier permissions from vMenu?

**Comment by Yanakis** [comment]
Nono it happens if i just run  the vMenu

**Comment by TomGrobbe** [comment]
@Yanakis But does it happen if you remove the permissions for torque/power multipliers in vMenu? That’s what I’m asking because then vMenu doesn’t interact with torque/engine power multipliers anymore

**Comment by Yanakis** [comment]
it happens if i enable any sub category from the "Vehicle Options, from the permissions.cfg file

**Comment by TomGrobbe** [comment]
@Yanakis Is this using custom vehicles or default gta v vehicles?

**Comment by Yanakis** [comment]
i test it on custom vehicles only
