### ISSUE TITLE
Weapon permissions

### ISSUE THREAD

**Issue by REDRUM216** [TomGrobbe/vMenu#114]
Im sorry if its stated somewhere, I've spent over a hour trying to figure this out and am left with no choice. 1 being weapon restrictions. I want certain guns available. The ones I dont want do not show up. But for the ones that I do want, it says Its locked when I try to equip it in the menu..

**Comment by TomGrobbe** [comment]
@REDRUM216 You need to allow players to spawn the weapon, see docs.vespura.com/vmenu/permissions-ref

**Comment by TomGrobbe** [comment]
@REDRUM216 As for the hitch warning whenever you start vMenu, that’s normal. Though it shouldn’t happen constantly after the server has been running for some time

**Comment by REDRUM216** [comment]
Wow, I some how never even seen that. Been working on it almost 12 hours straight. So minds misty.. Trying thats now. And I will let you know about it after running for a bit of time.

**Comment by REDRUM216** [comment]
It works, Thanks for your time Tom!

**Comment by REDRUM216** [comment]
One more thing, everyone can see Banned Players. Reason I notice is before I add any privileges to myself I want to see what pub players would.

**Comment by TomGrobbe** [comment]
@REDRUM216 Are you sure that isn’t just setup like that with permissions?

**Comment by TomGrobbe** [comment]
Just checked, and if the ban menu shows up for everyone, then that means everyone will be able to unban players... so you must’ve made a mistake somewhere because that’s probably not what you want.

**Comment by TomGrobbe** [comment]
@TomGrobbe (https://github.com/TomGrobbe/vMenu/blob/fa41d842e2f28a8e6949342e67b890298e2f731e/vMenu/MainMenu.cs#L579)

**Comment by REDRUM216** [comment]
Am I missing files? I dont have MainMenu.cs

**Comment by REDRUM216** [comment]
For some reason only I could see it. Maybe It inherited. Everything is working great so far. Thank you for your fast replies. One last question.

` add_ace group.admin "vMenu.VehicleOptions.All" allow
add_ace group.admin "vMenu.VehicleOptions.SpawnByName" allow
add_ace builtin.everyone "vMenu.VehicleSpawner.Menu" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.All" allow
add_ace builtin.everyone "vMenu.VehicleSpawner.DisableReplacePrevious" allow
add_ace builtin.everyone "vMenu.VehicleSpawner.Addon" allow # allows you to spawn an addon car from the Addon Vehicles list.
add_ace builtin.everyone "vMenu.VehicleSpawner.Compacts" allow `

For some reason as admin I have same permissions as builtin.everyone
I added this and still cant see spawn by menu. Or access any locked categories.

**Comment by TomGrobbe** [comment]
You're adding `"vMenu.VehicleOptions.SpawnByName"` it should be `"vMenu.VehicleSpawner.SpawnByName"`

**Comment by TomGrobbe** [comment]
(closed issue because the original issue has been solved, feel free to continue here if you still have problems)
