### ISSUE TITLE
voice chat distance default to 20m not 5m

### ISSUE THREAD

**Issue by Ultrunz** [TomGrobbe/vMenu#116]
Cant hear police when in a shop robbing it when they are outside. just feel that 20m is a better distance than 5m for the default. anyway to change it for everyone without letting them have access to the menu itself?

**Comment by TomGrobbe** [comment]
@Ultrunz Default is set to global, not 5. Unless you changed this yourself.
It’s user preference and everyone can set a default for themselves. Can’t be overridden by the server owner. You’d have to disable the voice chat menu all together and use something like vVoice if you want global server chat distance

**Comment by Ultrunz** [comment]
Yea I literally just came back to close this. It was my fault. I figured it out. Sorry to bother you :)
