### ISSUE TITLE
Can't Spawn Saved Vehicles if Vehicles Spawner menu is Disabled

### ISSUE THREAD

**Issue by BroCrafter14** [TomGrobbe/vMenu#117]
I'm not sure whether this is intentional or not, but in the instance of my server it's frustrating.
To be able to spawn Saved Vehicles I MUST enable the "Vehicle Spawner" tab, which I do not want.

See, my server is setup so that players have to go to physical places on the map to obtain, edit, fix and clean their vehicles. But I also want them to be able to save their customized vehicles and use them again in future sessions.

I will probably look into fixing it myself, but I thought I'd mention it as a thing just in case you didn't know.

Other than that I am really grateful for vMenu, it's really great and easy to use!

**Comment by TomGrobbe** [comment]
@BroCrafter14 Already added this ability in the last commits in the dev branch, and if you download the version i posted as a recent comment on the forum topic then you can already use this functionality.
