### ISSUE TITLE
Addon Vehicles menu not working 

### ISSUE THREAD

**Issue by Handlessragdoll** [TomGrobbe/vMenu#118]
My friend and I have added on vehicles that spawn in and can be spawned by name but, the addon menu is locked and it says "There are no addon vehicles on this server" We have tried to fix and we can not find a fix for it.

**Comment by TomGrobbe** [comment]
@Handlessragdoll You didn’t add the vehicles to the addons.json

**Comment by Handlessragdoll** [comment]
We have with their spawn names and it isnt working I can send screen shots
in a min eating rn

**Comment by TomGrobbe** [comment]
@Handlessragdoll If they’re not listed in the menu, then you either did not give them permissions for the menu or you did not add them to the file correctly.
Or you didn’t install them correctly.

**Comment by TomGrobbe** [comment]
@Handlessragdoll It works fine for everyone so it must be something wrong in your configuration

**Comment by Handlessragdoll** [comment]
Okay thank you

**Comment by Handlessragdoll** [comment]
Could you help set it up lol we tried everything

**Comment by TomGrobbe** [comment]
@Handlessragdoll Not right now, maybe later

**Comment by TheNakedRobbers** [comment]
@TomGrobbe  Can you show me an example on how it should look? I have installed all the cars I want and added there spawn name to the addon.json and the permissions are set correctly but still no luck! I have gone back 5 times and made sure thing are correct and so have both of my other admins.  This is the last thing I have to fix before the server can go live. Also an amazing menu!

**Comment by TheNakedRobbers** [comment]
Also, thank for the quick responses!

**Comment by TheNakedRobbers** [comment]
And I also have look at the permissions FAQ and followed the directions on how to enable the menu.

**Comment by TomGrobbe** [comment]
@TheNakedRobbers Show me your addons.json file (upload it to hastebin.com)

**Comment by TheNakedRobbers** [comment]
@TomGrobbe  give me a minute, now they want to spawn and the menu says to make sure they are streaming correctly.  had to re-upload part of the config file to get the menu to just unlock and actually display the json file.

**Comment by TheNakedRobbers** [comment]
{
  "vehicles": [
    "fmgt",
    "mst"
  ],
  "peds": [
    "addonpedname1",
    "addonpedname2"
  ],
  "weapons": [
    "addonweaponname1",
    "addonweaponname2"
  ]
}

**Comment by TheNakedRobbers** [comment]
@TomGrobbe  pasted it in hastebin but had no idea how to save it and send it to you.

**Comment by Handlessragdoll** [comment]
Hey man thanks for the help, its working now

**Comment by Orion13622** [comment]
How was this resolved?  Like TheNakedRobbers, I have the spawn names in the addons.json file along with admin permissions, however the addon vehicles shows all items locked.
