### ISSUE TITLE
Not working for 1920x1080 or screen size 

### ISSUE THREAD

**Issue by bluecars1234** [TomGrobbe/vMenu#122]
I have a Alienware 17 r4 17.3 and vmenu will not open on any server I join but it works for everyone else  I tried reinstalling fivem and gta still won’t sovle the problem can u please fix this 
Resolution 1920x1080

**Comment by TomGrobbe** [comment]
@bluecars1234 I have no idea what the issue could be. If it works fine for everyone except you then it must be something on your end.

**Comment by TomGrobbe** [comment]
@bluecars1234 Iow: I can’t fix it because I don’t know why it won’t work for you, because 1) I have absolutely no info about your case, and 2) it works fine for everyone so it’s probably not vMenu’s code itself causing problems, but rather something on your computer that breaks things

**Comment by bluecars1234** [comment]
Could u help me fix this please. What can caused that to happen

**Comment by bluecars1234** [comment]
Can we screen sure discord the other menus like Mello trainer works but not vmenu

**Comment by justweb1** [comment]
@bluecars1234 Check your keybindings to make sure you have the binding set for the action they are using to open the menu. I think by default it is the 'm' key which is set to the action 'open phone'.

**Comment by TomGrobbe** [comment]
>@bluecars1234 Check your keybindings to make sure you have the binding set for the action they are using to open the menu. I think by default it is the 'm' key which is set to the action 'open phone'.

M = open phone?! what? no! it's the interaction menu keybind for GTA:O

**Comment by bluecars1234** [comment]
I check it still doesn’t open.

**Comment by TomGrobbe** [comment]
@bluecars1234 there's nothing i can do, i don't know why it's not working, i can't debug on your pc. maybe it's a dependency on your computer that's messed up. or windows is broken or i don't even know what else it could be. Literally anything at this point.
