### ISSUE TITLE
Vehicle Despawn

### ISSUE THREAD

**Issue by XyCoDeLiC** [TomGrobbe/vMenu#123]
I found that vehicles despawn once they leave your sight, this doesn't happen with any other trainer. It would be great to just have the cars never despawn. Outstanding job with this Trainer. The best trainer out there by far! Wicked Job, keep it up!

**Comment by TomGrobbe** [comment]
@XyCoDeLiC This was fixed ages ago, and I need a repro for this if you want it fixed. It works fine for me and 99% of the other servers (or nobody bothers to report issues).

**Comment by XyCoDeLiC** [comment]
I have a freshly reloaded server and it Despawns the vehicles. I am working with another community and they are having the same issue. I am having this issue on both of my servers. Sorry, but what exactly is a repro?

**Comment by TomGrobbe** [comment]
@XyCoDeLiC Repro is reproduction. So basically I need a list of instructions on how exactly to reproduce this issue. Because testing on my own server shows no issues at all. So: which server artifacts version are you using, which resources are loaded, which features in vMenu are enabled related to spawning vehicles, which permissions do users have? Does it happen with x amount of players online? And things like that are all very helpful in finding a potential issue

**Comment by XyCoDeLiC** [comment]
Would you be willing to come check it out on our server? I will be able to give you access to the server and FTP. I am using Zap Hosting and everything is fully updated. Just let me know, then I can send you my Discord link, then you can have access to whatever you need. Amazing feedback, Thank you very much.

**Comment by XyCoDeLiC** [comment]
All other Resources have been disabled except for the Added Vehicles. It doesn't matter whether there is one person or many online, it despawns whenever no one is close to it. Also happens if only 1 car has been spawned. All spawning is enabled for Admin and I am set as Admin. Other users can only spawn there saved vehicles and GTA cars, but can't spawn by name. Those are the settings I used.

**Comment by TomGrobbe** [comment]
Does this despawning happen for _any_ (default) vehicle or only __addon__ or __replacement__ (streamed) vehicles?

**Comment by TomGrobbe** [comment]
and can you send me a [pastebin](https://pastebin.com) of your permissions.cfg?

**Comment by XyCoDeLiC** [comment]
https://pastebin.com/pDBhiWHD

**Comment by XyCoDeLiC** [comment]
I will test the default GTA cars now and report back ASAP.

**Comment by XyCoDeLiC** [comment]
All vehicles including the GTA cars despawn. It does the same on SARP server since the vMenu has been actived.

**Comment by XyCoDeLiC** [comment]
The Despawning seems to get worse the more cars you spawn. One car will still stay for a short distance, even if out of sight, but after spawning 4 cars, the disappear as you turn around.

**Comment by TomGrobbe** [comment]
which version of vMenu are you using?

**Comment by XyCoDeLiC** [comment]
the newest 5.0.3. Server reports it is up to date.

**Comment by TomGrobbe** [comment]
5.0.3? that's not even a vMenu version... I'm guessing 1.2.1 then. Did this issue also occur on v1.2.0? or any other previous builds?

**Comment by XyCoDeLiC** [comment]
my bad, checked the wrong line... lol
Yes, 1.2.1
We had this issue with the previous version too.

**Comment by XyCoDeLiC** [comment]
Just to make sure it isn't something I did, I just downloaded the latest version again and left the permissions default and did another test and the results are still the same.

**Comment by TomGrobbe** [comment]
I just downloaded a fresh server artifacts copy [(latest version)](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/787-bb55e8dd469ad9bce64097794713046aa526b040/) and a fresh copy of the github vMenu release (v1.2.1), installed the default fxserver resources from [here](https://github.com/citizenfx/cfx-server-data), spawned a car (tried default, replacement and addon cars) in the middle of the city, got a random car from the streets and drove all the way across the map, then back down, and every single time my spawned vehicle was still there. So it's probably not vMenu's fault, but rather another resource on your server deleting abandoned vehicles.

**Comment by XyCoDeLiC** [comment]
The offer is there to come test it on my server with full access. There are 3 servers that have the same problem. As mentioned, the server had nothing except vMenu running when I conducted my tests all weekend to be 100% sure it is the vMenu, before contacting you, but thank you for your time and feedback.

**Comment by TomGrobbe** [comment]
> The offer is there to come test it on my server with full access. There are 3 servers that have the same problem.

That's not an offer I can accept, for multiple reasons.
It won't solve anything.
All I can do is try to reproduce this issue myself, so I can debug code in vMenu at the same time and do many different tests. If you want, join my discord and pm me so you can try this out on my testing server to see if you can repro it there for me.

**Comment by TomGrobbe** [comment]
@TomGrobbe For anyone wondering: issue solved (was intended behaviour)
