### ISSUE TITLE
Pushing M Key not opening Menu

### ISSUE THREAD

**Issue by 320thSTSMilSim** [TomGrobbe/vMenu#124]
Hello,

So I've loaded vMenu into my server. I've used the menu before and then recently updated the server files with the latest server file update. My console shows it's loaded and is up to date. But, in game, I cannot open the menu. It won't do anything. No errors in console either. Fresh install of the resouce, so nothing was changed in the permissions.cfg. Please help! I love this menu and would really like to use it.

Thanks.

**Comment by TomGrobbe** [comment]
@320thSTSMilSim Do you get an error in the console saying there’s a problem with the addons.json file?

**Comment by 320thSTSMilSim** [comment]
No, no errors at all in console. Though when I tured on server debug, it showed me a lot of code and then my server crashed. Would that have anything to do with it?

**Comment by TomGrobbe** [comment]
>No, no errors at all in console. Though when I tured on server debug, it showed me a lot of code and then my server crashed. Would that have anything to do with it?

show me what that info was when the server crashed.

**Comment by 320thSTSMilSim** [comment]
Ah correction, wasn't server debug, it was client debug that gave the code. Here is it:

`Loaded vMenuServer.net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_1003908981
Stacktrace:


  at <unknown> <0xffffffff>

  at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&) [0x00016] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0

  at System.Reflection.MonoCMethod.InternalInvoke (object,object[]) [0x00007] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0

  at System.RuntimeType.CreateInstanceMono (bool) [0x000ab] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0

  at System.RuntimeType.CreateInstanceSlow (bool,bool,bool,System.Threading.StackCrawlMark&) [0x0000e] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0

  at System.RuntimeType.CreateInstanceDefaultCtor (bool,bool,bool,System.Threading.StackCrawlMark&) [0x0002d] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0

  at System.Activator.CreateInstance (System.Type,bool) [0x00041] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0

  at System.Activator.CreateInstance (System.Type) [0x00002] in <0123fd5b1a1040fe9d70a7e0d4b28acb>:0

  at CitizenFX.Core.InternalManager.CreateAssemblyInternal (byte[],byte[]) [0x00069] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore\InternalManager.cs:86

  at CitizenFX.Core.InternalManager.CreateAssembly (byte[],byte[]) [0x00000] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore\InternalManager.cs:71

  at (wrapper remoting-invoke-with-check) CitizenFX.Core.InternalManager.CreateAssembly (byte[],byte[]) [0x00034] in <d45d679fa983432890be32c72dfe41f3>:0

  at (wrapper xdomain-dispatch) CitizenFX.Core.InternalManager.CreateAssembly (object,byte[]&,byte[]&,byte[],byte[]) [0x00054] in <d45d679fa983432890be32c72dfe41f3>:0

  at (wrapper xdomain-invoke) CitizenFX.Core.InternalManager.CreateAssembly (byte[],byte[]) <0x00170>

  at (wrapper remoting-invoke-with-check) CitizenFX.Core.InternalManager.CreateAssembly (byte[],byte[]) [0x00028] in <d45d679fa983432890be32c72dfe41f3>:0

  at CitizenFX.Core.MonoScriptRuntime.LoadFile (string) <0x00315>

  at (wrapper cominterop) CitizenFX.Core.IScriptFileHandlingRuntime.LoadFile (intptr,string) <0x00049>

  at (wrapper native-to-managed) CitizenFX.Core.IScriptFileHandlingRuntime.LoadFile (intptr,intptr) <0x000e6>


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================`

**Comment by TomGrobbe** [comment]
That stacktrace is actually FXServer itself crashing, not vMenu crashing so it's not really useful for me sadly.

Send me a screenshot of what your vMenu folder looks like and the path of where it's installed.

**Comment by TomGrobbe** [comment]
You might be using a broken version of fxserver, or maybe even a corrupted file in vMenu, try updating/re-downloading both.

**Comment by 320thSTSMilSim** [comment]
I actually did that yesterday. Fresh downloaded files of the server files and downloaded vMenu from your github from the latest release. Tried it about 3 times.

**Comment by TomGrobbe** [comment]
@320thSTSMilSim i really have no clue what the issue could be if you're starting vMenu and not setting any convars, and you didn't change the keybindings...

**Comment by 320thSTSMilSim** [comment]
yeah, nothing. Just uploaded it to resources files, added the start in server.cfg and joined the server. So weird. Do you know of any other resources it might conflict with? Here is a list of my resources.
![list of resources](https://user-images.githubusercontent.com/16441364/46372192-481e8880-c63f-11e8-8f42-2a052a218c54.PNG)

**Comment by 320thSTSMilSim** [comment]
I have even tried the set key option in the server menu. Nothing seems to work. Shoot, really nice menu and loved it when it would open for me before.

**Comment by TomGrobbe** [comment]
@320thSTSMilSim nope i don't :/ if you enable client debugging mode, and try to open the menu, can you send me a client log after that?

**Comment by 320thSTSMilSim** [comment]
I'll see if I can get you one.

**Comment by 320thSTSMilSim** [comment]
I enabled client debug int he reource.lua. Do you know what the name of the debug file would be or where it would be located? Not seeing any logs being created?

**Comment by TomGrobbe** [comment]
The CitizenFX.log file inside your fivem application data (client files).

**Comment by 320thSTSMilSim** [comment]
hmmm doesn't seem to be creating one. Do you know if there is something I can put in the server.bat that starts the server to make it write a log?

**Comment by 320thSTSMilSim** [comment]
oh wait, sorry. you said client side...one moment.

**Comment by 320thSTSMilSim** [comment]
Hope this is the correct one. It has todays date and current time on it.
[CitizenFX.log](https://github.com/TomGrobbe/vMenu/files/2439548/CitizenFX.log)

**Comment by TomGrobbe** [comment]
```
[    249750] D:\Steam Games\steamapps\common\Grand Theft Auto V Newtonsoft.Json.dll is not a platform image.
[    249906] Error invoking callback for event vMenu:SetPermissions: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.Serialization.DefaultSerializationBinder' threw an exception. ---> System.MethodAccessException: Error verifying Newtonsoft.Json.Serialization.DefaultSerializationBinder:.ctor (): Method System.Runtime.Serialization.SerializationBinder:.ctor () is not accessible at 0x0018

[    250110]   at Newtonsoft.Json.Serialization.DefaultSerializationBinder..cctor () [0x00000] in <607e95f78559498690f968784b884761>:0 

[    250219]    --- End of inner exception stack trace ---

[    250250]   at Newtonsoft.Json.JsonSerializer.Create () [0x00000] in <607e95f78559498690f968784b884761>:0 

[    250328]   at Newtonsoft.Json.JsonSerializer.Create (Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <607e95f78559498690f968784b884761>:0 

[    250375]   at Newtonsoft.Json.JsonSerializer.CreateDefault () [0x00012] in <607e95f78559498690f968784b884761>:0 

[    250391]   at Newtonsoft.Json.JsonSerializer.CreateDefault (Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <607e95f78559498690f968784b884761>:0 

[    250485]   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <607e95f78559498690f968784b884761>:0 

[    250516]   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value) [0x00000] in <607e95f78559498690f968784b884761>:0 

[    250547]   at vMenuClient.MainMenu.SetPermissions (System.Object dict) [0x001c9] in <1f5b13d63ab3471e8f641fce862e4968>:0 

[    250578]   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Type,object)

[    250610]   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Type,object)

[    250656]   at vMenuClient.EventManager.UpdatePermissions (System.Object permissions) [0x00056] in <1f5b13d63ab3471e8f641fce862e4968>:0 

[    250688]   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)

[    250719]   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    250750]    --- End of inner exception stack trace ---

[    250781]   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    250891]   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    250922]   at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    250953]   at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    250985]   at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    251110]   at CitizenFX.Core.EventHandlerEntry+<Invoke>d__5.MoveNext () [0x00064] in C:\gl\builds\edf06b9b\0\cfx\fivem\code\client\clrcore\EventHandlerDictionary.cs:85 
[    251203] Error invoking callback for event vMenu:SetOptions: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.Serialization.DefaultSerializationBinder' threw an exception. ---> System.MethodAccessException: Error verifying Newtonsoft.Json.Serialization.DefaultSerializationBinder:.ctor (): Method System.Runtime.Serialization.SerializationBinder:.ctor () is not accessible at 0x0018

[    251328]   at Newtonsoft.Json.Serialization.DefaultSerializationBinder..cctor () [0x00000] in <607e95f78559498690f968784b884761>:0 

[    251360]    --- End of inner exception stack trace ---

[    251391]   at Newtonsoft.Json.JsonSerializer.Create () [0x00000] in <607e95f78559498690f968784b884761>:0 

[    251438]   at Newtonsoft.Json.JsonSerializer.Create (Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <607e95f78559498690f968784b884761>:0 

[    251469]   at Newtonsoft.Json.JsonSerializer.CreateDefault () [0x00012] in <607e95f78559498690f968784b884761>:0 

[    251500]   at Newtonsoft.Json.JsonSerializer.CreateDefault (Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <607e95f78559498690f968784b884761>:0 

[    251531]   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <607e95f78559498690f968784b884761>:0 

[    251563]   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value) [0x00000] in <607e95f78559498690f968784b884761>:0 

[    251594]   at vMenuClient.MainMenu.SetOptions (System.Object options) [0x0021d] in <1f5b13d63ab3471e8f641fce862e4968>:0 

[    251625]   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Type,object)

[    251672]   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Type,object)

[    251703]   at vMenuClient.EventManager.UpdateSettings (System.Object options) [0x00056] in <1f5b13d63ab3471e8f641fce862e4968>:0 

[    251735]   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)

[    251781]   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    251813]    --- End of inner exception stack trace ---

[    251844]   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    251875]   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    251906]   at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    251953]   at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    251985]   at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <a4e3abdd630b4c98a9d6f31a99197de6>:0 

[    252016]   at CitizenFX.Core.EventHandlerEntry+<Invoke>d__5.MoveNext () [0x00064] in C:\gl\builds\edf06b9b\0\cfx\fivem\code\client\clrcore\EventHandlerDictionary.cs:85 
```
it's something wrong with the newtonsoft json dll on your computer.... not sure if it fails to be sent through fivem or if a local version is broken. Have you tried re-installing GTA V and FiveM?

**Comment by 320thSTSMilSim** [comment]
i have yeah, but ill check the file.

**Comment by TomGrobbe** [comment]
Closing this because I sadly have no solution for this. Seems to be a broken file either on your server or on your PC. Reopen this if it turns into something I can fix myself.

**Comment by blockba5her** [comment]
Hey, I would like to update this issue because I found a temporary fix for it. Placing the version of `Newtonsoft.JSON.dll` that vMenu uses inside the `path/to/GTAV` directory will cause the dll to load and the menu to open.

**Comment by OnTheRoadWithBrett** [comment]
i am on a five m server and vMenu is working for everyone else in the server but not me

**Comment by TomGrobbe** [comment]
@OnTheRoadWithBrett have you tried the suggestion above?

**Comment by Dan-B1** [comment]
@TomGrobbe do i place the Newtonsofy.JSON.dll inside my GTA5 directory or where do i place it? Thanks!

**Comment by TomGrobbe** [comment]
>`path/to/GTAV` directory

so yeah in your GTA V folder....
