### ISSUE TITLE
Duplicating Cars

### ISSUE THREAD

**Issue by vicenetworkinc** [TomGrobbe/vMenu#125]
https://steamuserimages-a.akamaihd.net/ugc/946212099730799755/62A393268A6439111FD0D53D1AD0BEDD5491241F/

Recording Options causing Major server lag and duplicating cars when you hit it. 

Major texture loss

**Comment by TomGrobbe** [comment]
You need to disconnect from your current session first. So go to the misc settings > connection options > disconnect from session. Then open the rockstar editor.
