### ISSUE TITLE
Key/permission changing dose not work

### ISSUE THREAD

**Issue by Ezi2k** [TomGrobbe/vMenu#127]
While changing keys to open or use noclip nothing happens same with permission system. And i've no clue why.

```lua
# Any valid control ID can be used here.
setr vmenu_menu_toggle_key 107
setr vmenu_noclip_toggle_key 108
```

**Comment by TomGrobbe** [comment]
Are you actually executing the permissions file? Are you sure you're restarting the server each time you make a change to the permissions file?

**Comment by Ezi2k** [comment]
Yes Sir i'm.
But there is some issues while executing the config.

`exec exec resources/vMenu/config/permissions.cfg
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
No such command setr.
`

**Comment by TomGrobbe** [comment]
@Ezi2k you're not using an updated server, use fxserver version 801 or later

**Comment by Ezi2k** [comment]
@TomGrobbe Alright, will try thanks!

**Comment by Ezi2k** [comment]
Same issue, and i'm using this version of FXServer for Linux [LinuxFX](https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/revoked/)

**Comment by TomGrobbe** [comment]
@Ezi2k You're using a 5 months old REVOKED version... obviously that'll cause all sorts of issues!
Use this: https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/807-a33d6db066568046a9a99b14b0fccb03bb978e2f/
