### ISSUE TITLE
When vMenu is running, phone not working

### ISSUE THREAD

**Issue by tomteipl** [TomGrobbe/vMenu#134]
when I receive a call, I do not hear me or the caller.
And when you disable vMenu from config then everything works.
Any ideas ? 

sorry fo my english...Google translate

**Comment by TomGrobbe** [comment]
vMenu does not disable other resources. Must be the other resource crashing/conflicting with vMenu but since you didn’t provide any info about what resource it is, or follow the bug report format I can’t do shit about it.
