### ISSUE TITLE
UI issues ultrawide

### ISSUE THREAD

**Issue by CryptoGenics** [TomGrobbe/vMenu#137]
**Describe the bug**
UI messed up for ultrawide monitor Text displays further right then UI background.

**To Reproduce**
1. use ultrawide aspect ratio (2560x1080) 21:9

**Screenshots**
![unknown](https://user-images.githubusercontent.com/45253987/50258800-e3193a00-03c6-11e9-90b3-723a7ee507c7.png)

**vMenu Info**:
- vMenu Version (check the about menu): 2.1.0

**Comment by TomGrobbe** [comment]
Left align the menu in the misc settings menu to solve this. Right aligned menus are not supported for those aspect ratios. Because the script gfx align natives fuck that up with text.
This is not a vMenu issue, but rather a menuapi issue.
