### ISSUE TITLE
VMenu Loading error? I THINK???

### ISSUE THREAD

**Issue by destrokin** [TomGrobbe/vMenu#138]
**Describe the bug**
I cannot play any FiveM Server With VMenu Like *AT ALL*.
I know i installed FiveM Correctly cause i showed a friend how to do it and his works.
Ive Reinstalled the game 3 times *FULLY*.

When i join a server with a VMenu On it I get the error at the bottom of this post.
*#ALittleSadeImTheOnlyOneWithThisIssue*

**To Reproduce**
No Freaking Clue.

**Expected behavior**
Join games and use the Menu Propperly
**Screenshots**
![capture](https://user-images.githubusercontent.com/19646487/50477332-8652ec00-0991-11e9-9629-cf7b611713da.PNG)

**vMenu Info**: Dont Know What to out here
- Server ip: ALL with VMenu
- vMenu Version (check the about menu): Latest
- Do you have access to the files? No
- FXServer artifacts version: Latest

**Additional context**
 I can open it on some servers but all i can use it the online players section.

**Comment by destrokin** [comment]
If possible Getback to me on discord if u can help me fix **DISCORD:** Destrokin#0246

**Comment by TomGrobbe** [comment]
@destrokin Join my discord if you want me to help you on discord. It’s on my site.

**Comment by TomGrobbe** [comment]
@destrokin https://www.vespura.com/
