### ISSUE TITLE
Removing weapons incompatibility

### ISSUE THREAD

**Issue by amakuu** [TomGrobbe/vMenu#140]
Its incompatible with esx_ambulancejob.
Player after revive/respawn lost his weapons (no matter how it is configurated in ambulancejob)

Is there a way to disable retrive weapons etc. In Vmenu??

Bug started after the last update of vmenu

**Comment by TomGrobbe** [comment]
vMenu does not remove any weapons on re-spawn. That's done by spawnmanager. vMenu only has the option to _restore_ those weapons (give them back after you respawn). However, if you mess with the 'death' state of the player then vMenu might not be able to restore them correctly, this is not vMenu's fault, but rather another resource that changes the death state of the player and/or removes weapons/forces a re-spawn.

You can turn off vMenu's weapon restore option in the misc settings menu.
