### ISSUE TITLE
Ped Customization not working

### ISSUE THREAD

**Issue by ralvarez710** [TomGrobbe/vMenu#141]
**Describe the bug**
The bug happens when you go to ped customization.

**To Reproduce**
1. Go to 'Ped Customization'
2. Click on 'any clothing or accessory option'
3. See error

**Expected behavior**
The ped clothing should switch upon changing numbers of the clothing. Instead the clothing does not change and I have to hit enter for the clothing to change.
**Screenshots**

**vMenu Info**:
- Server ip: 167.160.88.194
- vMenu Version (check the about menu): Newest
- Do you have access to the files? Yes
- FXServer artifacts version: Newest.

**Additional context**

**Comment by ralvarez710** [comment]
![image](https://user-images.githubusercontent.com/39890165/50945842-9b854b80-1464-11e9-95b0-41dabc38c19d.png)

**Comment by TomGrobbe** [comment]
Already fixed here: https://github.com/TomGrobbe/vMenu/commit/84d99febf82cc157afa343a41225e6c796ef06e8 also in beta builds, but there’s other bugs there. New release is planned for this Friday to fix every issue.

**Comment by TomGrobbe** [comment]
Just FYI, it’s only an issue for player appearance menu, and only props are affected. Mp peds customization menu is completely unaffected

**Comment by ralvarez710** [comment]
Thanks Problem is we use a custom SMY cop 01 ped and cant change the clothing options we have for him

**Comment by TomGrobbe** [comment]
@ralvarez710 Unless all clothing options are props, you should still be able to change some things.

**Comment by TomGrobbe** [comment]
@ralvarez710 You can try the beta build but it’s probably unstable, use at your own risk. Link to those is on the main topic somewhere.
