### ISSUE TITLE
Not able to change ped addons under "ped customization"

### ISSUE THREAD

**Issue by CodenameHaswell** [TomGrobbe/vMenu#142]
**As I was typing this I read that you will be releasing an update this Friday. So I will be patient, but what is a fix that I can use for now?**

**Describe the bug**
Not able to change ped addons under "ped customization"

**To Reproduce**
1. Go to 'Ped customization'
2. Try to change anything

It seems to change textures by hitting enter, but won't change the model props by scrolling through hats/glasses/shirts/pants/etc. I've tried it with addon peds, as well as stock GTA/FiveM peds.

**Expected behavior**
I expected to be able to change hats, glasses, shirts, pants, etc.

**Screenshots**
Not Applicable

**vMenu Info**:
- Server ip: play.sar-rp.com
- vMenu Version (check the about menu): 2.1.0
- Do you have access to the files? Yes.
- FXServer artifacts version: Build 1002 (Newest as of today 1-10-2019) Also had the same issue before I Updated

**Additional context**
I thought it may have been something I have installed that conflicted,  but I don't have anything installed to do with peds except 3 addon peds. It was working a few days ago, I tried clearing cache serverside/clientside, no avail. Tried reinstalling vMenu from scratch, nothing. Also, I saved a ped from before when it was working. & it loads fine with hats/glasses etc, so I'm sure its not a model issue because they load fine when I spawn it using "Saved Peds".

**Comment by TomGrobbe** [comment]
https://github.com/TomGrobbe/vMenu/issues/141 duplicate
