### ISSUE TITLE
Menu wont load. Single client only.

### ISSUE THREAD

**Issue by Starystars67** [TomGrobbe/vMenu#143]
**Describe the bug**
I have received a report from a client on my server that the vMenu does not load for them. This is a single client only.
Looking at the clients .log i have noticed this:
```
[    214391] Error invoking callback for event vMenu:SetPermissions: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.Serialization.DefaultSerializationBinder' threw an exception. ---> System.MethodAccessException: Error verifying Newtonsoft.Json.Serialization.DefaultSerializationBinder:.ctor (): Method System.Runtime.Serialization.SerializationBinder:.ctor () is not accessible at 0x0001

[    214406]   at Newtonsoft.Json.Serialization.DefaultSerializationBinder..cctor () [0x00000] in <dc86da7fc46c487ba6c7ab826da479cc>:0 
```

**To Reproduce**
There are no noticable steps to reproduce the error. This has only been experienced on one client.

**Expected behavior**
The menu should work, sorry for the bluntness.

**Screenshots**
![image](https://user-images.githubusercontent.com/15389482/51285817-34c5dc00-19e8-11e9-93b4-f6681aa40720.png)

**vMenu Info**:
- Server ip: 95.216.35.232:30130
- vMenu Version (check the about menu): 2.2.0
- Do you have access to the files? Yes
- FXServer artifacts version: 979

**Additional context**
Such as:

- A list of allowed permissions for the player that is having this issue: Default sent with the resource.
- A list of enabled/disabled vMenu features: As it comes with the resource. and with custom.

Both of these can very easily be provided by using `/vmenuclient dump` while in-game and sending the CitizenFX.log file (`FiveM Application Data\CitizenFX.log`) from that same game session.
Log: 
[CitizenFX (46).log](https://github.com/TomGrobbe/vMenu/files/2766589/CitizenFX.46.log)

**Comment by TomGrobbe** [comment]
Your client newtonsoft.json file is broken. Try downloading vMenu, taking the `Newtonsoft.Json.dll` file from the download, and placing that in your GTA V installation folder. I've heard some people solve this issue that way.

Alternatively, try re-installing GTA V and FiveM.

**Comment by Starystars67** [comment]
Excellent i have just heard back and that worked thank you!
