### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by ralvarez710** [TomGrobbe/vMenu#145]
**Describe the bug**

**To Reproduce**
1. Start Server and get error 
2. [vMenu] [WARNING] vMenu is set up to ignore permissions!
If you did this on purpose then you can ignore this warning.
If you did not set this on purpose, then you must have made a mistake while setting up vMenu.
Please read the vMenu documentation (https://docs.vespura.com/vmenu).
Most likely you are not executing the permissions.cfg (correctly).
**Screenshots**
![image](https://user-images.githubusercontent.com/39890165/51887789-f1ae2600-2362-11e9-8a6c-b6f7fa7d2a32.png)

**vMenu Info**:
- Server ip:192.154.226.110
- vMenu Version (check the about menu): 2.2.1
- Do you have access to the files? Yes
- FXServer artifacts version: 1026-5ad0ca2272add5510ae99394418a622941fb0ef7 (Most Recent)

**Additional context**
Such as:

- A list of allowed permissions for the player that is having this issue.
- A list of enabled/disabled vMenu features.

Both of these can very easily be provided by using `/vmenuclient dump` while in-game and sending the CitizenFX.log file (`FiveM Application Data\CitizenFX.log`) from that same game session.
[CitizenFX.log](https://github.com/TomGrobbe/vMenu/files/2806334/CitizenFX.log)

This zip has the server config and permissions files

**Comment by ralvarez710** [comment]
@TomGrobbe I guess my question is where did I go wrong? and where can I fix it. I read through the wiki and I literally copied the permissions folder and had set a file path for the exec.

**Comment by TomGrobbe** [comment]
@ralvarez710 I just joined your server, and there's nothing wrong. it is using the permissions setup correctly. there's nothing indicating that error message at all.

**Comment by ralvarez710** [comment]
@TomGrobbe Not sure why i am still getting that error though. I will test it tonight when more people are on to see if i can kick and ban.

**Comment by ralvarez710** [comment]
I was able to fix the permission not being seen but I still cant get the menus to allow me to kick or ban.

**Comment by ralvarez710** [comment]
Solved

**Comment by TomGrobbe** [comment]
@ralvarez710 👌🏻 alright well in that case this closes #145
