### ISSUE TITLE
Using with GcPhone

### ISSUE THREAD

**Issue by DayZen16** [TomGrobbe/vMenu#149]
**Describe the bug**
As soon as we enable vMenu onto the server our gcphone's voice calling does not transmit. If we remove it it works again. I have tried to disable by removing from permissions completely but the admins still have access and it affects their phones. 

**To Reproduce**
Install Gcphone,
Install vMenu

**vMenu Info**:
- vMenu Version (check the about menu): 2.2.1
- Do you have access to the files? Yes
- FXServer artifacts version: 961

**Comment by TomGrobbe** [comment]
@DayZen16 Easy fix: disable vMenu's voice chat options completely by removing the permissions. I know you already said you did that, but you also mentioned admins still have access to it. So, remove access for ALL groups.
