### ISSUE TITLE
Fix the NPC list

### ISSUE THREAD

**Issue by TomUSOSA** [TomGrobbe/vMenu#150]
Please fix the NPC list so that its not just 12 lists with the spawnnames. for example you could make it like in lambda where it says the name and shit.

also add the possibility to spawn props.

**Comment by TomGrobbe** [comment]
@TomUSOSA Fix what. Nothing about the list is even broken. The names are the real names, why would I be using made up names.
vMenu is not a mapeditor so no spawning objects will probably never be added
