### ISSUE TITLE
Check if player is in vehicle for MP Ped menu

### ISSUE THREAD

**Issue by h0kkaido** [TomGrobbe/vMenu#153]
**Players are able to enter MP customization menu while in car**
Basically, it would be nice to check if player is in the vehicle because MP customization menu throws a player out the vehicle, which leads to a camera displacement and some funny stuff.

**To Reproduce**
1. Get some fancy car
2. Go to 'vMenu'
3. Go fast like sonic
4. Click on 'MP Ped Customization'
5. Done!

**Expected behavior**
Camera displacement and, if you are lucky, player on the shoulder of the highway.

**vMenu Info**:
- vMenu Version (check the about menu): 2.2.2

**Comment by TomGrobbe** [comment]
Will do this later. 👍🏻
