### ISSUE TITLE
Staff actions webhook

### ISSUE THREAD

**Issue by miniDeathStriker** [TomGrobbe/vMenu#156]
**Describe the bug**
The staff actions webhook doesn't seem to work. 

**To Reproduce**
1. Have the webhook set up
2. Kick someone.
3. Observe your channel

**Expected behavior**
Expect it to send a webhook message.

**Screenshots**
http://prntscr.com/msk2gs (blurred out token (its a valid token))

**vMenu Info**:
- Server ip: 173.74.43.76:30110 
- vMenu Version (check the about menu): 2.2.1
- Do you have access to the files? yes
- FXServer artifacts version: 1056-07194cf7b489d61b1400c516aab75b73eb69068f (newest feb 16)

**Additional context**
Such as:

- A list of allowed permissions for the player that is having this issue.
- A list of enabled/disabled vMenu features.
[CitizenFX.log](https://github.com/TomGrobbe/vMenu/files/2923053/CitizenFX.log)
https://pastebin.com/8ffAA3QX

Both of these can very easily be provided by using `/vmenuclient dump` while in-game and sending the CitizenFX.log file (`FiveM Application Data\CitizenFX.log`) from that same game session.

**Comment by TomGrobbe** [comment]
There is no webhook feature built in to vMenu...

**Comment by Doxylamin** [comment]
Sicne the name of the convar is "ea_moderationNotificiation" I assume it's an issue for [Bluethefurry/EasyAdmin](https://github.com/Bluethefurry/EasyAdmin).

**Comment by miniDeathStriker** [comment]
Yea, sorry. got a bit confused
