### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by Harrychandler71** [TomGrobbe/vMenu#159]
Permissions aren't registering. I am using the hex from my steam account. Could someone please help me out. Contact me on discord H. Chandler#7023

**Comment by TomGrobbe** [comment]
Permissions work fine. You must've made a mistake setting them up. If you want support you can either join my discord server and ask in the vMenu support channel, or you can ask for help on the forum topic. This is not the place to ask for help, and no I won't add you on discord, that's not how support works, you don't just ask someone to contact you if _you_ want to have support.

**Comment by Harrychandler71** [comment]
Hi, thanks for your reply. I’ve figured it out. The Permissions.cfg was being executed after the vMenu was opened.
