### ISSUE TITLE
The menu has no language options

### ISSUE THREAD

**Issue by yangzhi311** [TomGrobbe/vMenu#160]
If possible, can you add a **_language_** module?
External configuration language files, modify menu list names, etc.
For example, **_en.lua_** and **_fr.lua_** or **_en.json_** and **_fr.json_** so on.
This allows more players to accept vMenu.
If possible, open an external interface that allows users to add their own native language packages.
**This software is very good**, if you can improve the proposed function module is even better!

**Comment by TomGrobbe** [comment]
Would require the entire resource to be rewritten, most likely won't happen. Also please post feature requests on the existing issue, don't create new issues for this.
