### ISSUE TITLE
GlobalError: <<unknown pool>> Pool Full, Size == 1500

### ISSUE THREAD

**Issue by kasuganosoras** [TomGrobbe/vMenu#162]
**Describe the bug**
GlobalError: <<unknown pool>> Pool Full, Size == 1500 (you need to raise <<unknown pool>> PoolSize in common/data/gameconfig.xml)

**To Reproduce**
1. Start FiveM
2. Join any server installed vMenu
3. The game start lagging
4. Open the game console and see error

**Expected behavior**
Play the game normally

**Screenshots**
![img](https://i.natfrp.org/345fa2121f270ffa724f6dd10727291b.png)
![img](https://i.natfrp.org/ef204255e1e8605ac59c3544ad66908b.png)

**vMenu Info**:
- Server ip: `play.akkariin.com`
- vMenu Version (check the about menu): v2.1.0
- Do you have access to the files? Yes
- FXServer artifacts version: Unknown

**Additional context**
CitizenFX.log file: https://cdn.tcotp.cn:4443/assets/CitizenFX.log
This problem appears after I update FiveM. The game is lagging when I join any server installed vMenu. When I open the game console, I saw this error:
```
[   1392656] GlobalError: <<unknown pool>> Pool Full, Size == 1500 (you need to raise <<unknown pool>> PoolSize in common/data/gameconfig.xml)
[   1392656] InvokeNative: execution failed: Error executing native 0x0ce3aa5e1ca19e10 at address 0x1415f78b8.
[   1392672] Failed to run a tick for FunctionsController: System.ArgumentException: Value does not fall within the expected range.
[   1392672]   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR (System.Int32 errorCode) [0x0000a] in <f0e9de1592254c6a8c7c298c474f20de>:0 
[   1392672]   at CitizenFX.Core.InternalManager+DirectScriptHost.InvokeNative (System.IntPtr context) [0x00018] in C:\gl\builds\edf06b9b\0\cfx\fivem\code\client\clrcore\InternalManager.cs:450 
[   1392672]   at CitizenFX.Core.ScriptContext.InvokeInternal (System.UInt64 nativeIdentifier, CitizenFX.Core.IScriptHost scriptHost) [0x00014] in C:\gl\builds\edf06b9b\0\cfx\fivem\code\client\clrcore\ScriptContext.cs:277 
[   1392672]   at CitizenFX.Core.ScriptContext.Invoke (System.UInt64 nativeIdentifier, CitizenFX.Core.IScriptHost scriptHost) [0x00000] in C:\gl\builds\edf06b9b\0\cfx\fivem\code\client\clrcore\ScriptContext.cs:266 
[   1392672]   at CitizenFX.Core.ScriptContext.Invoke (System.UInt64 nativeIdentifier) [0x00000] in C:\gl\builds\edf06b9b\0\cfx\fivem\code\client\clrcore\ScriptContext.cs:263 
[   1392672]   at CitizenFX.Core.Native.API.InternalDecorSetInt (System.Int32 entity, System.String propertyName, System.Int32 _value) [0x0001b] in C:\gl\builds\edf06b9b\0\cfx\fivem\code\client\clrcore\NativesFive.cs:31829 
[   1392672]   at CitizenFX.Core.Native.API.DecorSetInt (System.Int32 entity, System.String propertyName, System.Int32 _value) [0x00000] in C:\gl\builds\edf06b9b\0\cfx\fivem\code\client\clrcore\NativesFive.cs:31818 
[   1392672]   at vMenuClient.FunctionsController+<PlayerClothingAnimationsController>d__51.MoveNext () [0x003d6] in F:\Project\vMenu\vMenu\FunctionsController.cs:1662 
```

I tried to raise the `DecoratorExtension` and `Decorator` value from 1500 to 8192 in `common/data/gameconfig.xml`.
It work, the game started to get smooth. But after a few minutes, the game is become lagging.

When I killed myself in game, the game is get smooth. But the problems is appear again after a few minutes.

Please forgive my English grammar wrong, I am Chinese. 😄

**Comment by TomGrobbe** [comment]
This is caused by client side mods like manual transmission/gears.asi

**Comment by kasuganosoras** [comment]
> This is caused by client side mods like manual transmission/gears.asi

Thank, I tried to delete the `gears.asi` and now the game is working. But I have a question, before the FiveM update, the manual transmission is working fine. Maybe is something conflict? I want to use Logitech game wheel to drive car in game, what should I do?

**Comment by TomGrobbe** [comment]
Currently almost all manual transition client side mods have known conflicts. They register way too many decorators, so it appears to be a bug in those mods, which then conflicts if vMenu wants to register just 2... There's nothing that I can do about this sadly.

**Comment by E66666666** [comment]
>They register way too many decorators

Actually it was an old assumption of mine that everybody should unlock the decorator registration, register their decorators, and re-lock it again. Apparently this recent update in FiveM only unlocks it at the start and leaves it open for scripts to do their thing, but doesn't consider the thing can be closed again.

In any case, [I added a workaround](https://ci.appveyor.com/project/E66666666/gtavmanualtransmission/build/artifacts), but I don't feel inclined to release it every time FiveM changes something internally again.

**Comment by TomGrobbe** [comment]
> Actually it was an old assumption of mine that everybody should unlock the decorator registration, register their decorators, and re-lock it again. Apparently this recent update in FiveM only unlocks it at the start and leaves it open for scripts to do their thing, but doesn't consider the thing can be closed again.

I wasn't trying to point any fingers at any particular one. I've just had reports of people that it was multiple transmissions mods that caused it, that's all i know.

I didn't know FiveM changed anything related to decorators recently. Though glad you've decided to provide a workaround this time, appreciate it. 🙂

**Comment by kasuganosoras** [comment]
Thank you. It works very well now :p

![img](https://i.natfrp.org/3feb32de3326888647101a77d5f4cf0d.png)
