### ISSUE TITLE
no animal peds (option is activated)

### ISSUE THREAD

**Issue by Heady20006** [TomGrobbe/vMenu#163]
**Describe the bug**
i´ve activated the option spawn as an animal but it doesnt work.
the option is still deactivated

**To Reproduce**
1. Go to 'Player Related Options'
2. Go to 'Player Appearance'
3. Go to 'Spawn Peds'

**Expected behavior**
i´ve expected to use the option to spawn a an animal :)

**vMenu Info**:
- Server ip: 78.31.64.75:30121
- vMenu Version (check the about menu): 3.0.2.
- Do you have access to the files? yes
- FXServer artifacts version: 1159

**Additional context**
Such as:

- permission system is disabled so everyone can use the vMenu (its just on my Testserver)

Both of these can very easily be provided by using `/vmenuclient dump` while in-game and sending the CitizenFX.log file (`FiveM Application Data\CitizenFX.log`) from that same game session.

**Comment by TomGrobbe** [comment]
You probably aren't executing the permissions.cfg or something because i've tested it and it works absolutely fine.

**Comment by TomGrobbe** [comment]
If you have logs or any other useful info feel free to provide that content here.

**Comment by Heady20006** [comment]
yes it worked :) thx a lot.
