### ISSUE TITLE
vMenu Exception loading assembly error

### ISSUE THREAD

**Issue by Dvginkel** [TomGrobbe/vMenu#164]
**Describe the bug**

On a Fresh install of FX-server and vMenu, vMenu is not opening in-game. I checked the console output and found some output which doesnt appear when i remove vMenu from resources and server.cfg.

I have made a pastebin with full output when i start server untill its sends its first heartbeat.  [console_log](https://pastebin.com/1XdcMe4x)

**To Reproduce**
(Server im running it on is a VPS with ubuntu 16.04.)
1. Install a fresh copy of FX-Server according the docs.
2. Install a fresh copy of vMenu according the docs.
3. Start server
4. See an 'Exception loading...' in console and vMenu is not opening in-game.

**Expected behavior**
From what i read in vMenu docs i see that it should work after following install doc.

**Screenshots**
Pastbin link for output: [console_log](https://pastebin.com/1XdcMe4x)

**vMenu Info**:
- Server ip: 178.20.169.203:30121 (server is offline atm)
- vMenu Version (check the about menu): 3.0.1 / 3.0.2 (i tried both versions)
- Do you have access to the files? i have root access 
- FXServer artifacts version: 1141-8cded82ebff9053946e778016cb496acd0e250b0/

**Additional context**

Unknown for me at this point.

Most recent [CitizenFX.log](https://pastebin.com/4nrRAity) file.

**Comment by TomGrobbe** [comment]
https://docs.vespura.com/vmenu/changelog/#important (open the 3.0.1 spoiler).

**Comment by Dvginkel** [comment]
> https://docs.vespura.com/vmenu/changelog/#important (open the 3.0.1 spoiler).

I kinda feel stupid ^_^ but i replaced files and now it works like a charm. 

Thanks!
