### ISSUE TITLE
Vehicle spawner doesn't remove/mark as non-persistent if has occupants

### ISSUE THREAD

**Issue by imckl** [TomGrobbe/vMenu#168]
**Describe the bug**
When spawn new vehicle from spawner/load existed, it doesn't remove or mark as non-persistent.

Code below logic shows when _previousVehicle gets any occupants and LocalPlayer is not the driver, replacePrevious check will never got called.
This might leave _previousVehicle alone as persistent entity.

**Problematic code**
```

vMenuClient -> CommonFunctions.cs -> SpawnVehicle (~line 1024)
            // If the previous vehicle exists...
            if (_previousVehicle != null)
            {
                // And it's actually a vehicle (rather than another random entity type)
                if (_previousVehicle.Exists() && _previousVehicle.PreviouslyOwnedByPlayer &&
                    (_previousVehicle.Occupants.Count() == 0 || _previousVehicle.Driver.Handle == Game.PlayerPed.Handle))
                {
                    // If the previous vehicle should be deleted:
                    if (replacePrevious || !IsAllowed(Permission.VSDisableReplacePrevious))
                    {
                        // Delete it.
                        _previousVehicle.PreviouslyOwnedByPlayer = false;
                        SetEntityAsMissionEntity(_previousVehicle.Handle, true, true);
                        _previousVehicle.Delete();
                    }
                    // Otherwise
                    else
                    {
                        if (!vMenuShared.ConfigManager.GetSettingsBool(vMenuShared.ConfigManager.Setting.vmenu_keep_spawned_vehicles_persistent))
                        {
                            // Set the vehicle to be no longer needed. This will make the game engine decide when it should be removed (when all players get too far away).
                            SetEntityAsMissionEntity(_previousVehicle.Handle, false, false);
                            //_previousVehicle.IsPersistent = false;
                            //_previousVehicle.PreviouslyOwnedByPlayer = false;
                            //_previousVehicle.MarkAsNoLongerNeeded();
                        }
                    }
                    _previousVehicle = null;
                }
            }

```
**Screenshots**
![_H04)R127C0QP014OT 6{(1](https://user-images.githubusercontent.com/20377660/55896316-9c0eb900-5bf0-11e9-8e41-e01fe24dfb73.png)
![W GLCDM%FGQ_W$`IV@62@V](https://user-images.githubusercontent.com/20377660/55896318-9d3fe600-5bf0-11e9-8f6a-80ecc3de1239.png)

**vMenu Info**:
- vMenu Version (check the about menu): 3.0.2
- Do you have access to the files?
- FXServer artifacts version: 1159

**Note**:
If this confirms to be an issue, I would like to submit PR to resolve it.

**Comment by TomGrobbe** [comment]
This is intentional to not delete vehicles that other players are using. Also because at that point your client no longer has access to the vehicle if you exit it and the other players are now in it. Unless you're trying to say something im not seeing right now?

**Comment by imckl** [comment]
> This is intentional to not delete vehicles that other players are using. Also because at that point your client no longer has access to the vehicle if you exit it and the other players are now in it. Unless you're trying to say something im not seeing right now?

Sorry, I didn't claim clearly for this issue.
I agree the point that not to delete vehicles that other players are using.
Current issue is that SetEntityAsMissionEntity will never get called if any players in the vehicle when owner trying to spawn a new vehicle. 
If SetEntityAsMissionEntity is intent to use to set vehicle as (non-)persistent, and then this vehicle will keep persistent. This might lead to entity leaks or something like that?
I'm not fully walking through code logic of SapwnVehicle, sorry if I were go through wrong.

**Comment by TomGrobbe** [comment]
this is not used to keep it (not) persistent. That native doesn't work like that. Setting it as a mission entity is only done when deleting vehicles. To make vehicles persistent `SetVehicleHasBeenOwnedByPlayer` is used instead.

**Comment by TomGrobbe** [comment]
Setting a vehicle as no longer needed using `SetVehicleAsNoLongerNeeded` or `SetEntityAsNoLongerNeeded` will make the game de-spawn the car whenever it's no longer in any visible range of any player.

**Comment by imckl** [comment]
I've checked into API docs, and it said SetEntityAsMissionEntity is to use to make the specified entity persistent:
![image](https://user-images.githubusercontent.com/20377660/56132374-608f3880-5fbc-11e9-9231-58b2eb516cb4.png)

SetEntityAsNoLongerNeeded is to use like you said:
![image](https://user-images.githubusercontent.com/20377660/56132458-97fde500-5fbc-11e9-8d7b-c9f3ea12f397.png)

Unfortunately, SetVehicleHasBeenOwnedByPlayer has no remark:
![image](https://user-images.githubusercontent.com/20377660/56132494-b1069600-5fbc-11e9-9667-70adba38b94e.png)

**Comment by TomGrobbe** [comment]
What API docs is this that you're using? Because the CFX C# API actually uses `Vehicle.IsPersistent` which uses the `SetVehicleHasBeenOwnedByPlayer` native.

**Comment by imckl** [comment]
I view API by ILSpy:
![image](https://user-images.githubusercontent.com/20377660/56132879-bdd7b980-5fbd-11e9-89af-2050f05e3356.png)

Also, VS 2017 C# intellisense indicates that (packaged from Nuget -> CitizenFX.Core.Client -> v1.0.1175:
![image](https://user-images.githubusercontent.com/20377660/56132987-f8d9ed00-5fbd-11e9-9ba5-baeb9f925ab9.png)
![image](https://user-images.githubusercontent.com/20377660/56133046-1ad36f80-5fbe-11e9-8d0a-14ec193c01c4.png)

**Comment by TomGrobbe** [comment]
Apparently IsPersistent doesn't use that. Because it's an Entity function instead. Still, doesn't matter. It's not needed to make vehicles (not) persistent.

**Comment by imckl** [comment]
> What API docs is this that you're using? Because the CFX C# API actually uses `Vehicle.IsPersistent` which uses the `SetVehicleHasBeenOwnedByPlayer` native.

I've rechecked in source and find Entity.IsPersistent (inherit by Vehicle) use both SetEntityAsMissionEntity  and SetEntityAsNoLongerNeeded to set persistent state
![image](https://user-images.githubusercontent.com/20377660/56378951-1ec2f400-6241-11e9-8d11-a781f1f12390.png)

![image](https://user-images.githubusercontent.com/20377660/56379063-68abda00-6241-11e9-96be-3ab85ee49b9b.png)

![image](https://user-images.githubusercontent.com/20377660/56379056-65185300-6241-11e9-9fb9-b0ed5c5a5680.png)


BTW, in my test, the destoryed vehicles are still remain on ground, even if I've traveled far long way from them.

**Comment by TomGrobbe** [comment]
> I've rechecked in source and find Entity.IsPersistent (inherit by Vehicle) use both SetEntityAsMissionEntity and SetEntityAsNoLongerNeeded to set persistent state


i know, that's what i mentioned after that:

> Apparently IsPersistent doesn't use that. Because it's an Entity function instead. Still, doesn't matter. It's not needed to make vehicles (not) persistent.

**Comment by imckl** [comment]
> > I've rechecked in source and find Entity.IsPersistent (inherit by Vehicle) use both SetEntityAsMissionEntity and SetEntityAsNoLongerNeeded to set persistent state
> 
> i know, that's what i mentioned after that:
> 
> > Apparently IsPersistent doesn't use that. Because it's an Entity function instead. Still, doesn't matter. It's not needed to make vehicles (not) persistent.

Thanks, I've got the point :)
