### ISSUE TITLE
Textual inaccuracy when banning

### ISSUE THREAD

**Issue by schwim0341** [TomGrobbe/vMenu#169]
**Describe the bug**
Player A banned player B permanently.
Issue 1) Ingame, it stated that player schwim **temporarily** banned player B
Issue 2) In server log it stated: 
```
[vMenu] [SUCCESS] [BAN] A new ban record has been added. Player: 'A' was banned by 'B' for 'It is time to find a new home.' until '1/1/3000 12:00:00 AM'.
```

**To Reproduce**
1. Ban someone permanently
2. Watch ingame notice and server terminal for text.

**Expected behavior**
1) Ingame, a permanent ban should state that the player was banned permanently.
2) It shouldn't reverse the banner and bannee.
**Screenshots**

**vMenu Info**:
- Server ip: scotchandiron.org
- vMenu Version (check the about menu): 3.0.2
- Do you have access to the files? yes
- FXServer artifacts version:  latest linux

**Comment by TomGrobbe** [comment]
>Ingame, a permanent ban should state that the player was banned permanently.


Not sure what you're implying here?


>It shouldn't reverse the banner and bannee.


This was already fixed [here](https://github.com/TomGrobbe/vMenu/commit/a909ed4f000ab01fa60e5d25c9257f146c2cd4f8). Just use this version for now: https://forum.fivem.net/t/vmenu-v3-0-2-a-server-sided-menu-including-almost-full-permissions-support/88868/3357?u=vespura

**Comment by schwim0341** [comment]
> Not sure what you're implying here?

Not sure how else to say it.  If I click the "Ban permanently", it shouldn't say I temporarily banned the player until the year 3000.  Since I chose permament ban link in the menu, the resulting success text should state that I permanently banned the player.

**Comment by TomGrobbe** [comment]
>Not sure how else to say it. If I click the "Ban permanently", it shouldn't say I temporarily banned the player until the year 3000. Since I chose permament ban link in the menu, the resulting success text should state that I permanently banned the player.

Ah, that's fixed in the commit referenced above. It's because internally the same function is used for both. So I've just removed the 'temp' from that and just made it "has been banned"

**Comment by TomGrobbe** [comment]
>I temporarily banned the player until the year 3000.

Also that's not even anywhere... So it's impossible to get a message that looks like that, unless you've implemented it yourself. It's either "Ban time remaining ...." or "you are banned until ..." or something similar. But it never tells the staff member anything like that.

**Comment by schwim0341** [comment]
I didn't say it told the other player that but with this latest round of complete misunderstanding, I give up.  I'll leave the error reporting to others.  Thanks for the great resource.

**Comment by TomGrobbe** [comment]
huh? I appreciate you reporting this. I just got confused _who_ received _what_ exact message.

**Comment by attributeerror** [comment]
From what I understand, the server log it saying that the moderator was banned by the banned player, so that needs switching around. Then, in game, the moderator is being told the player is **temporarily** banned even though they selected to **permanently** ban the player.

**Comment by TomGrobbe** [comment]
>From what I understand, the server log it saying that the moderator was banned by the banned player, so that needs switching around.

>Then, in game, the moderator is being told the player is temporarily banned even though they selected to permanently ban the player.

These are two separate issues.
Both have been fixed. One was already fixed earlier, and one today.

**Comment by schwim0341** [comment]
I should have taken a screenshot but didn't think to in time and I'm apparently terrible at explaining what had happened.  The moderator received a notice above the minimap that the player had been temporarily banned after he had chosen to permanently ban the player.  I'm sorry for the poor explanation of the issue.

**Comment by TomGrobbe** [comment]
No problem, though that's simply impossible. There's no code at all that sends a notification like that to any client.
