### ISSUE TITLE
vMenu failure to load vMenuServer.net.dll

### ISSUE THREAD

**Issue by Roaldado** [TomGrobbe/vMenu#170]
I installed vMenu step by step as stated on the vesupura.com website but I get a error saying it fails to load the vMenuServer.net.dll script (see screenshot attached). I'm relatively new to FiveM servers, so excuse me if it's an easy fix. Thanks in advance anyways.

**Screenshots**
https://imgur.com/a/jtzCYhC

**vMenu Info**:
- Server ip:185.114.225.32
- vMenu Version (check the about menu): 3.0.2
- Do you have access to the files? Yes
- FXServer artifacts version: No idea, latest I guess

**Comment by TomGrobbe** [comment]
https://forum.fivem.net/t/vmenu-v3-0-2-a-server-sided-menu-including-almost-full-permissions-support/88868?u=vespura

**Comment by TomGrobbe** [comment]
Read the known issues please.
