### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by LySoon** [TomGrobbe/vMenu#172]
![image](https://user-images.githubusercontent.com/49767982/56394151-0eaa1500-623f-11e9-95bc-2d8c5bd0f9e1.png)

**Comment by TomGrobbe** [comment]
Random issue that is know to occur sometimes, but the cause is unknown because there's no useful info at all for me to even start looking into it.

**Comment by LySoon** [comment]
So is it harmfull ?? Or just a error that looks deadly but not harmfull at all ?

**Comment by Hugamara** [comment]
Nah, we got the same thing. My suspect is anything to deal with special characters and a ban log? Only started happening after that. It is a fatal error and if you close the error it will shut down the server.

https://i.imgur.com/2WFPgM1.png

**Comment by TomGrobbe** [comment]
It is a fatal error, but so far I’ve not had anyone tell me anything about things like “what user(name) got banned when this occurred” so I can’t check what characters may cause this.

**Comment by LySoon** [comment]
My server was in testing progress and i didnt banned anyone yet.. just kicked one ppl but it was about 2 days ago..

**Comment by TomGrobbe** [comment]
yeah it sometimes just 'randomly' occurs, no idea why.
