### ISSUE TITLE
Error - Failed to run a tick for MenuController

### ISSUE THREAD

**Issue by HumanTree92** [TomGrobbe/vMenu#174]
**Describe the bug**
The Bug only happens if for example you disable everyone from accessing vMenu.PlayerOptions.Menu

**To Reproduce**
Set it up so Everyone only has access to the follow
add_ace builtin.everyone "vMenu.PersonalVehicle.Menu" allow
add_ace builtin.everyone "vMenu.PersonalVehicle.ToggleEngine" allow
add_ace builtin.everyone "vMenu.PersonalVehicle.ToggleLights" allow
add_ace builtin.everyone "vMenu.PersonalVehicle.SoundHorn" allow
add_ace builtin.everyone "vMenu.PersonalVehicle.ToggleAlarm" allow
add_ace builtin.everyone "vMenu.PersonalVehicle.AddBlip" allow
add_ace builtin.everyone "vMenu.VehicleOptions.Menu" allow
add_ace builtin.everyone "vMenu.VehicleOptions.Engine" allow
add_ace builtin.everyone "vMenu.VehicleOptions.Doors" allow
add_ace builtin.everyone "vMenu.VehicleOptions.Windows" allow
add_ace builtin.everyone "vMenu.VehicleOptions.NoHelmet" allow
add_ace builtin.everyone "vMenu.VehicleOptions.Components" allow

**Expected behavior**
It will throw a Resource Time Warning & throw the Failed to run a tick for MenuController in the Logs.

**Screenshots**

**vMenu Info**:
- Server ip: 192.151.157.170:30120
- vMenu Version (check the about menu): 3.0.2
- Do you have access to the files? Yes
- FXServer artifacts version: Latest Version. I stay up to date.

**Additional context**
Such as:

- A list of allowed permissions for the player that is having this issue.
- A list of enabled/disabled vMenu features.

Both of these can very easily be provided by using `/vmenuclient dump` while in-game and sending the CitizenFX.log file (`FiveM Application Data\CitizenFX.log`) from that same game session.

**Comment by HumanTree92** [comment]
Here is my Permissions File if u want to look. For now i added everyone the ability to use the player options even though i don't like the ability for players to commit suicide.
[My Perms.zip](https://github.com/TomGrobbe/vMenu/files/3110448/My.Perms.zip)

**Comment by TomGrobbe** [comment]
This can be fixed if you manually download the latest version of MenuAPI and use that in your vMenu folder (replace the MenuAPI.dll file). I would push a vMenu version to fix this but appveyor is currently broken so I can't.
