### ISSUE TITLE
how do i install vMenu to my fiveM server im confused and cant seem to get it working?

### ISSUE THREAD

**Issue by iBeBlasts** [TomGrobbe/vMenu#175]

**Comment by daniel96rk** [comment]
https://docs.vespura.com/vmenu/

**Comment by iBeBlasts** [comment]
> https://docs.vespura.com/vmenu/

i dont have money to pay for one i just need to figer out how to get vMenu to work

**Comment by TomGrobbe** [comment]
Huh? You don’t need to pay anyone? It’s just a link to the documentation that explains how to install vMenu, even for new people. Just follow the instructions and it will work fine.
