### ISSUE TITLE
Client Freeze on Resource Start/Restart/Stop

### ISSUE THREAD

**Issue by daniel96rk** [TomGrobbe/vMenu#176]
**Describe the bug**
Everytime a resource is restarted/started on our server while running, the FiveM client freezes and the process needs to be terminated. This does not appear to be the case with vMenu v3.0.2. Another note is that if the FiveM client is frozen due to the bug above and you shut down the server, the process resumes and starts working again. 

**To Reproduce**
Steps to reproduce the behavior: Restart or start any resource while the FiveM server is running.

Temp fix: Revert to another version of vMenu.

**Comment by TomGrobbe** [comment]
Need more info

**Comment by TomGrobbe** [comment]
The current info you provided is not enough, I can not reproduce this issue. So if you have more info feel free to reply, if you don’t have more information then I can’t fix it because currently it does not seem to be a vMenu issue at all.
