### ISSUE TITLE
Memory issue when user presses M (locked down permissions)

### ISSUE THREAD

**Issue by CHARLESJ5** [TomGrobbe/vMenu#177]
**Describe the bug**
We have locked down vMenu to be used by only Moderators/Admins. As such, when a normal user presses M, they get a memory error in the bottom right of their screen. Pressing M again makes it go away but it is an annoyance.

**To Reproduce**
1. Lock down permissions to Mod/Admin on all options
2. Join server as a normal user
3. Press M

**Expected behavior**
Pressing M should not show a memory error.

**vMenu Info**:
- vMenu Version (check the about menu): 3.0.2
- Do you have access to the files? Yes
- FXServer artifacts version: v1.0.0.1141 linux

**Comment by TomGrobbe** [comment]
Update vMenu
