### ISSUE TITLE
vMenu Appears with No Access Granted for Everyone

### ISSUE THREAD

**Issue by CHARLESJ5** [TomGrobbe/vMenu#179]
**Describe the bug**
I upgraded as you suggested, and now everyone can open vMenu and use the Recording and Misc Settings. All permissions are set to either `group.everyone` or `group.admin`.

Adding `add_ace group.everyone "vMenu.MiscSettings.All" deny` to the config does not help.

**Expected behavior**
vMenu should not show for non moderator or admin.

**Screenshots**
https://i.gyazo.com/d0b584ade0555c11ef3b0064424a1411.png

**vMenu Info**:
- vMenu Version (check the about menu): 3.0.3

**Comment by TomGrobbe** [comment]
You didn’t make the menu staff only probably
