### ISSUE TITLE
İn game admins can access vmenu with full perm

### ISSUE THREAD

**Issue by LySoon** [TomGrobbe/vMenu#183]
When i give admin or super admin to some one.. he can access to vMenu too..
V menu is only for staff
How can i fix that ?
İ changed vmenu permissions to vmenu but still wont work

**Comment by TomGrobbe** [comment]
'admin' or 'superadmin' are generally considered 'staff' members. So vMenu's default group names are group.moderator and group.admin, both have the vMenu.Staff permission.

**Comment by LySoon** [comment]
Soo where can i change it :?
From permissions ??

**Comment by TomGrobbe** [comment]
@LySoon well change the group.admin to something else in the permissions.cfg

**Comment by LySoon** [comment]
Thank you so much
Sir Tom ❤️
