### ISSUE TITLE
its not working with a new version of mysql Async

### ISSUE THREAD

**Issue by amakuu** [TomGrobbe/vMenu#184]
as in title

**Comment by TomGrobbe** [comment]
no info = no fix

**Comment by amakuu** [comment]
![image](https://user-images.githubusercontent.com/29600503/57467737-60185380-7283-11e9-8a7b-0f5a8b70bd6a.png)
Errors from console, it stopped working after i updated mysql-async.

**Comment by TomGrobbe** [comment]
well you did something else other than _just_ updating mysql-async, because this error has nothing to do with mysql, it's just your server is outdated and/or you didn't add the required files if you're using linux. So yeah just read the known issues on the forum topic.
