### ISSUE TITLE
vMenu wont start on linux

### ISSUE THREAD

**Issue by LySoon** [TomGrobbe/vMenu#185]
the config and cfg is same as the windows server...
everything works but vMenu wont start up or wont say that 
vMenu is up to date , Good Job !
![image](https://user-images.githubusercontent.com/49767982/57459144-512da300-727b-11e9-8aaf-1090cca51542.png)

Essential is working as you see but vMenu wont start

**Comment by TomGrobbe** [comment]
@LySoon essentialmode is completely unrelated to vMenu. Provide actual info for me to work with or don't bother creating an issue in the first place, thanks.

**Comment by LySoon** [comment]
![image](https://user-images.githubusercontent.com/49767982/57461034-f433ec00-727e-11e9-8bed-6638e94419a6.png)


here there is some errors

**Comment by kotykk** [comment]
Try to read known issues on the FiveM forum (https://forum.fivem.net/t/vmenu-v3-0-3-a-server-sided-menu-including-almost-full-permissions-support/88868)

**Comment by Doxylamin** [comment]
Read the **IMPORTANT** section in the [v3.0.1 Release](https://github.com/TomGrobbe/vMenu/releases/tag/v3.0.1)

**Comment by LySoon** [comment]
Thank you @Doxylamin it fixed my issue..
didn't saw something about linux ^^
Thanks
