### ISSUE TITLE
mic not working with version 3.0.0

### ISSUE THREAD

**Issue by dnrpserver** [TomGrobbe/vMenu#186]
**Describe the bug**
i have someone in my server that can not speak in game with vmenu versions 3.0.0 and above

**vMenu Info**:
- Server ip: 192.99.221.49:32030
- vMenu Version (check the about menu): 3.0.0
- Do you have access to the files? yes
- FXServer artifacts version:

**Additional context**
Such as: fivem forum location https://forum.fivem.net/t/server-muted-in-certain-servers/505224

- A list of allowed permissions for the player that is having this issue.
admin

**Comment by TomGrobbe** [comment]
Not a vMenu issue.
