### ISSUE TITLE
test title?

### ISSUE THREAD

**Issue by Caprini4613** [TomGrobbe/vMenu#187]
I just switcher server hosts to citadel and im on a 64 slot server, i transferred all files from filezilla, i loaded in and vMenu worked but told me it was outdated, i updated it and now i i get a menu that says test title, with options test, bool, int, and string. i took out the files and put in my original and now it wont work

**Comment by TomGrobbe** [comment]
@Caprini4613 There’s no such thing as a “test menu with test title and options: test, bool, int, and string” in vMenu at all. So pretty sure you’re confusing it for another resource.
