### ISSUE TITLE
I can't enable input for vMenu when dead (esx_ambulancejob)

### ISSUE THREAD

**Issue by MoravianLion** [TomGrobbe/vMenu#188]
I would like to enable vMenu start button (F10) in when dead with esx_ambulancejob (for admins/moderators) - I can enable other buttons, but vMenu won't show up when ped is dead and need EMS 

from esx_ambulancejob

              if IsDead then
			DisableAllControlActions(0)
			EnableControlAction(0, Keys['G'], true) - have been here already
			EnableControlAction(0, Keys['T'], true) - have been here already
			EnableControlAction(0, Keys['E'], true) - have been here already
			EnableControlAction(0, 57, true)    - F10 for vMenu doesn't work
			EnableControlAction(0, 344, true)  - F11 for scoreboard (IDs) work
		else
			Citizen.Wait(500)
		end

vMenu is 3.0.3

**Comment by TomGrobbe** [comment]
@MoravianLion You can’t enable or disable vMenu’s toggle key. There’s nothing you can do to open or prevent vMenu from opening. Also, vMenu will automatically close if the player is dead.
