### ISSUE TITLE
Issue Opening vMenu

### ISSUE THREAD

**Issue by vicenetworkinc** [TomGrobbe/vMenu#189]
**Describe the bug**
When you press the menu open button it will give a hitch time and in f8 throws this error 
![image](https://user-images.githubusercontent.com/42921621/58219216-df177e00-7cbe-11e9-9150-0b74d151527d.png)

**To Reproduce**
Press F1 (Key Changed)
Errors Spam

**Expected behavior**
This error spams.
![image](https://user-images.githubusercontent.com/42921621/58219232-ec346d00-7cbe-11e9-91a6-5e6d723ddf29.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/42921621/58219237-f2c2e480-7cbe-11e9-8e19-d238302248a5.png)

**vMenu Info**:
- Server ip: 66.70.180.150
- vMenu Version (check the about menu): 3.0.2
- Do you have access to the files? yes
- FXServer artifacts version: 1259

**Comment by TomGrobbe** [comment]
@vicenetworkinc Update vMenu
