### ISSUE TITLE
When i ban some one.. other players cant join to the server

### ISSUE THREAD

**Issue by LySoon** [TomGrobbe/vMenu#192]
When i ban a hacker or some one like them..

normal players will be unable to join the server.. they r seeing the same ban message as hacker..

**Comment by TomGrobbe** [comment]
@LySoon Then they have one of the same identifiers

**Comment by LySoon** [comment]
İm sure they not.. (if u mean smthng like the game downloaded via same steam etc)


Or if u mean steam hex.. no they not same hex adresses... Because when a manager banned a hacker.. i was unable to join my own server..

İ was only able to join after i deleted vmenubans file..
