### ISSUE TITLE
How to enable spawn animals

### ISSUE THREAD

**Issue by theyellowguy** [TomGrobbe/vMenu#195]
This is cause of bugs disabled by server owner but I want to enable it, but I can't find how.

**Comment by TomGrobbe** [comment]
maybe read the docs or look inside the permissions.cfg for the default configuration option?

**Comment by theyellowguy** [comment]
I looked into both, but I couldn't find anything in it. That's why 'm asking for it :-)

**Comment by theyellowguy** [comment]
FInally found it. Thanks.
