### ISSUE TITLE
Bug When Spawning Saved ped Gives max ammo. 

### ISSUE THREAD

**Issue by GarridoR10** [TomGrobbe/vMenu#198]
**Describe the bug**
So this happens when spawning a Model saved by the Player appearance tabor the MP Player Customization. Every time i spawn a ped I get full ammo from my weapon.

**To Reproduce**
1. Go to 'Player appearance spawn a ped from "Saved Chras" with an empty gun and that's it you have full ammo

**Screenshots**

**vMenu Info**:
- Server ip:134.255.231.11:30120
- vMenu Version (check the about menu):Last Release
- Do you have access to the files?

- A list of allowed permissions for the player that is having this issue.
- A list of enabled/disabled vMenu features.

**Comment by TomGrobbe** [comment]
Fixed.

**Comment by hemato** [comment]
> Fixed.

if i download last version . is it fixed ?

**Comment by TomGrobbe** [comment]
Latest dev builds yeah.

**Comment by hemato** [comment]
> Latest dev builds yeah.

http://prntscr.com/ofzucd

is this one ?

**Comment by TomGrobbe** [comment]
@hemato no that's not a dev build, dev builds are on appveyor

**Comment by hemato** [comment]
appveyor.yml ? 
vmenu.sln

is this one ? with visual studio ?

**Comment by hemato** [comment]
> @hemato no that's not a dev build, dev builds are on appveyor

appveyor.yml ?
vmenu.sln

is this one ? with visual studio ?

**Comment by TomGrobbe** [comment]
no. it's literally on the forum topic. you can find the link there.
