### ISSUE TITLE
changing key to open NoClip, text in menu is wrong

### ISSUE THREAD

**Issue by EDWernars** [TomGrobbe/vMenu#199]
**Describe the bug**
I change the key of NoClip to F10, only in the menu to close NoClip its said; F2 to close menu.

**To Reproduce**
1. Change default key to F10
2. Open menu with F10
3. And see for closing menu that you need to press F2 (but it's actually F10)

**Expected behavior**
In the menu needs to change F2 to the key that I have set in the config (F10)

**Screenshots**

**vMenu Info**:
- vMenu Version (check the about menu): 3.0.3
- Do you have access to the files?: Yes
- FXServer artifacts version: newest
- ESX Version: 6.2.2

**Comment by TomGrobbe** [comment]
Where exactly does it say this?

**Comment by EDWernars** [comment]
If you activate this, it stay on the right bottom corner.

**Comment by TomGrobbe** [comment]
@EDWernars Do you have a screenshot because I’m not sure what you mean. If you mean the instructional buttons then I’ve already changed that. Not sure how long ago exactly but quite while.

**Comment by EDWernars** [comment]
Yeah I meant the instructional buttons, in the version that i'm using it's not fixed but I would update this week to check it out. Thanks!

**Comment by Hydra312** [comment]
so i when i install vMenu, add exec permissions.cfg

i get
```No such command setr.```
i also get 
```failed to load script vMenuserver.net.dll```

its a home hosted server

**Comment by scandula-c** [comment]
>i get
No such command setr.
i also get
failed to load script vMenuserver.net.dll

its a home hosted server

That's totally irrelevant to this issue.
