### ISSUE TITLE
Onesync

### ISSUE THREAD

**Issue by Bissen569** [TomGrobbe/vMenu#200]
**Describe the bug**
Basically it feels like Vmenu and Onesync doesn't go 100% well together, while it is smooth at most times we experience a few hiccups here and there, sometimes when you spectate people your game will crash, even with voice chat turned off in vmenu sometimes the current speaker icon in the top center flickers even though you are not near anyone and no one is talking. 

**To Reproduce**
spectating will crash instantly, but sometimes it works without any issues.
the current speak will just flicker randomly

**Expected behavior**
i would like to know if theres anywhere in vmenu i need to prepare it for onesync like for i 0.32 to 255. I haven't been able to find any.

**vMenu Info**:
- Server ip:
- vMenu Version (check the about menu):
- Do you have access to the files?
- FXServer artifacts version:

- A list of allowed permissions for the player that is having this issue.
the spectate bug will happend for anyone who has permissions to use it, but as stated only once in a while.
the current speak will happend for everybody

- A list of enabled/disabled vMenu features.
i will disable vmenu voicechat so that might fix it.

**Comment by TomGrobbe** [comment]
@Bissen569 Then you didn’t turn off voice chat properly. No access or no voice chat enabled means no voice chat related code will run on vMenu at all.

**Comment by Bissen569** [comment]
Great, ye the flickering was not really to big of a deal, but when spectating either you crash once you spectate or after a little while spectating. 
Thats why i was wondering if i needed to change anything in Vmenu for it to function with onesync since this issue wasnt there before we enabled onesync

**Comment by TomGrobbe** [comment]
@Bissen569 Also note that vMenu just uses natives. And if the game apparently thinks that someone is talking when they’re not, and vMenu displays that, it’s because the game indicates that they are. It’s not because vMenu randomly decides someone is speaking. It’s a FiveM/mumble bug.

Same for the spectating crash. If you crash during spectating that’s probably just because of spectating being buggy in that case. Try using another resource to spectate someone and see if you’re still getting these crashes.

**Comment by Bissen569** [comment]
Allso when we enabled onesync it seems that everyone can see names and ID's above heads and allso that everyone can see map blips. even though you try to turn it off in Vmenu, i'm not sure if this has anything to do with Vmenu or just the fact that onesync does that by default, but i thought since you are such a talented developer you might have an idea on the issue?

**Comment by TomGrobbe** [comment]
@Bissen569 You must have another resource doing that. OneSync does not have that by default and if you turn it off in vMenu, then it really is turned off and vMenu will not create those blips or overhead names.
