### ISSUE TITLE
vMenu error

### ISSUE THREAD

**Issue by ElectroTTV** [TomGrobbe/vMenu#201]
[vMenu] Checking for updates. [vMenu] [WARNING] An error occurred while checking for the latest version. This is not a problem, vMenu will still work correctly. Please check your version manually. [vMenu] Error info: Unexpected character encountered while parsing value: U. Path '', line 0, position 0.

When you try to enter the server you can see only the loading screen

**Comment by TomGrobbe** [comment]
That's not a vMenu problem. Also note that vMenu message is just a warning that you probably don't have internet access. It's not an error.
vMenu never prevents you from joining the server.

**Comment by ElectroTTV** [comment]
when shutting down vMenu Normally everything works

**Comment by TomGrobbe** [comment]
Any errors? Because without errors i can't do anything. Either server or client side.
