### ISSUE TITLE
Nametag above player

### ISSUE THREAD

**Issue by MrSmilesMore** [TomGrobbe/vMenu#202]
So on my server, I see everyone's nametag above their player, but no one else but me sees that, I am unaware of why I see that, I've checked all my vmenu settings but I'm pretty sure it is from vmenu.

**Comment by TomGrobbe** [comment]
Only if it's enabled in vMenu's settings will it generate those. By default, the resource `playernames` is installed on every server and also activated, so check that first. Also update to vMenu's dev build if you want to fix a permissions issue regarding the overhead names.
