### ISSUE TITLE
Mini Map stuck on expanded on new version

### ISSUE THREAD

**Issue by TheStonedRaider** [TomGrobbe/vMenu#205]
**Describe the bug**
The minimap is expanded to its bigger size. and there is no option to change it. I've tried searching though my server code for something else that changing it and there is nothing. 
Also tried to use commands to change it to small but it will not go. 
Changing the option in the setting does nothing also. 

**To Reproduce**
updated to new version. Some people are saying they now have the expanded map. 

**Expected behavior**
not this lol. 

 
**Screenshots**

**vMenu Info**:
- Server ip:  188.208.32.202:30120
- vMenu Version (3.0.3):
- Do you have access to the files? yes, 
- FXServer artifacts version: ive been updating daily. no change. currently 1.0.0.1428

**Additional context**
I searched my whole server for the lines 
SetBigmapActive
SET_BIGMAP_ACTIVE
SetMinimapOverlayDisplay
IsBigmapActive
AddMinimapOverlay

no results except for vMenu. 

- A list of allowed permissions for the player that is having this issue.
- A list of enabled/disabled vMenu features.

Both of these can very easily be provided by using `/vmenuclient dump` while in-game and sending the CitizenFX.log file (`FiveM Application Data\CitizenFX.log`) from that same game session.

**Comment by TomGrobbe** [comment]
@TheStonedRaider Not a bug, they just have to turn off the expanded radar option in their pause menu settings.

**Comment by TheStonedRaider** [comment]
Ah well that's not what it says in the changelog
"No longer toggle the mini-map radar size when the control for it is disabled (by another resource or mod)." , so I was looking in the resources or mods.
Hence the confusion. It needs to say that it looks at the main menu option aswell. 
Thanks

**Comment by TomGrobbe** [comment]
@TheStonedRaider that's not what changed in there though. That was already implemented and wasn't changed... so why would I mention that in the changelog when it hasn't even changed?

**Comment by TheStonedRaider** [comment]
Then Mention it overall.  SOMWHERE would have avoided this for me and I'm sure for a few other peeps. no need to get sarcastic.

**Comment by TomGrobbe** [comment]
@TheStonedRaider It has been mentioned on the forum topic before multiple times, as well as in my discord. If you CTRL + F on the forum topic, it opens up the search bar of discourse, allowing you to search for any posts in that topic containing something like "expanded radar" (which would bring up this post for example: https://forum.fivem.net/t/vmenu-v3-0-3-a-server-sided-menu-including-almost-full-permissions-support/88868/3370?u=vespura). Also, don't really see the issue of you just asking and me then giving an answer to solve the problem?
