### ISSUE TITLE
Some staff members are not able to access functions.

### ISSUE THREAD

**Issue by ResqDiver1317** [TomGrobbe/vMenu#207]
**Describe the bug**
We have a few staff members that despite adding their HEX to the permissions file, they are still unable to use the functions that should be available to them (and are available to other staff members). I noticed these same staff members also have the same problem with our Admin Panel. They show up in the panel as players, but it looks like it is not capturing their Steam ID when they join the server so vMenu and our admin panel both don't recognize them as staff as both refer to their HEX. 

**To Reproduce**
1. Add new staff member
2. Staff member logs in and either their ID is "registered and they are fine or it is not "registered" and they cannot use the staff functions in vMenu.

**Expected behavior**
I expect their ID to be captured allowing the access to both the vMenu and Staff panel functions. 

**Screenshots**

**vMenu Info**:
- Server ip: 185.249.169.3
- vMenu Version (check the about menu): 3.0.3
- Do you have access to the files? yes
- FXServer artifacts version: Not sure

**Additional context**
I understand this may be a FiveM issue, not a vMenu issue, but I'm hoping maybe someone here would might have some insight on what I can do to fix the issue. 

- A list of allowed permissions for the player that is having this issue.
- A list of enabled/disabled vMenu features.

Both of these can very easily be provided by using `/vmenuclient dump` while in-game and sending the CitizenFX.log file (`FiveM Application Data\CitizenFX.log`) from that same game session.

**Comment by TomGrobbe** [comment]
This has to be user error. vMenu gets the permissions from the server as executed via the permissions.cfg. If you've entered the wrong ID then they won't have access to vMenu because the server will not have their permissions properly loaded.
