### ISSUE TITLE
duplicating bullets and broken teleport

### ISSUE THREAD

**Issue by Rokas22** [TomGrobbe/vMenu#209]
Hello, so as i said bullets are duplicating using this menu or more. For example if you`re using esx and you have like 30 bullets, after you die and someone revives you (an admin or ambulance) your bullets will duplicate. Also if you have 0 bullets and get revived, you`ll get full pistol of bullets (1k bullets). Another thing is teleporting system. If you have ambulance job running, sometimes teleport will glitch out and everytime you try to teleport it will teleport you to the hospital door (where teleport is set to get inside). After that you get instantly invisible, god mode and freeze so you have to use menu to turn it on and off if you want to walk. And the last bug i found was again using ambulance job. If i get bug that i mentioned before (with teleporting), every revived person gets teleported to the same teleport to hospital, being dead and hanging in the air.

**Comment by TomGrobbe** [comment]
The incorrect ammo count has been fixed already in dev builds. However the compatibility issues with the "ambulance job" regarding teleports is something I can't fix, most likely the "ambulance job" resource is preventing teleports from working correctly.
