### ISSUE TITLE
Updated vMenu getting this error "SQLite error: SQL logic error no such table: bans"

### ISSUE THREAD

**Issue by lorentedford** [TomGrobbe/vMenu#210]
**Describe the bug**
[vMenu] [ERROR] [DEBUG LOG] SQLite error: SQL logic error
no such table: bans
server thread hitch warning: timer interval of 189 milliseconds
Sending heartbeat to live-internal.fivem.net:30110
Sending heartbeat to live-internal.fivem.net:30110
Sending heartbeat to live-internal.fivem.net:30110
[vMenu] [ERROR] [DEBUG LOG] SQLite error: SQL logic error
no such table: bans
Sending heartbeat to live-internal.fivem.net:30110

**To Reproduce**
1. Go to 'Console'
2. Click on 'Join Server'
3. Scroll down to 'Newest Messages in Console'

**Expected behavior**
I expect as much as possible the least amount of errors in my console in fact I am striving for no errors.
**Screenshots**
![fivem vmenu error](https://user-images.githubusercontent.com/8719903/63387852-210e9980-c36c-11e9-981a-6860f2c887e4.png)

**vMenu Info**:
- Server Public ip:157.185.79.38
- vMenu Version (vMenu v3.03)
- Do you have access to the files? Yes!
- FXServer artifacts version:Don't believe i am running FXServer.. Centos Linux.
Linux jennagangrp.ltcraft.net 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
Such as: I recently updated the server to the latest version and the cfx server data. I am thinking this might be a bug of some sort.

Below seems Not Applicable to my error.
```
- A list of allowed permissions for the player that is having this issue.
- A list of enabled/disabled vMenu features.

Both of these can very easily be provided by using `/vmenuclient dump` while in-game and sending the CitizenFX.log file (`FiveM Application Data\CitizenFX.log`) from that same game session.

```

**Comment by TomGrobbe** [comment]
The bans database file is corrupted most likely, delete it and try again.

**Comment by TomGrobbe** [comment]
Linux is extremely unstable with SQLite. So the best thing to do is use a windows vps, or setup vMenu to use the bans.json instead of SQLite.
