### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Retrull1** [TomGrobbe/vMenu#214]
I am getting this error in my cmd when starting my server 
![Capture](https://user-images.githubusercontent.com/55243623/64788906-c6590e00-d5b6-11e9-95fe-4162b3187e60.PNG)

it is really annoying plz help

**Comment by Retrull1** [comment]
i have idk what is going on

**Comment by T-Caster** [comment]
Another very common misconception: “vMenu doesn’t read the permissions file, my permissions don’t work, I need help!” vMenu does NOT read the permissions.cfg file. You execute the permissions.cfg file yourself by adding exec <pathToPermissionsFile>/permissions.cfg to your server.cfg. The commands inside the permissions.cfg will then be executed by the server. THEY ARE NOT EXECUTED BY vMenu!!! vMenu simply ‘asks’ the server “Is this player allowed to do <insert permission name here>, and the server will then return true or false. vMenu does not know at all about the permissions.cfg itself.
