### ISSUE TITLE
Cant unban people

### ISSUE THREAD

**Issue by wolgix** [TomGrobbe/vMenu#215]
**Describe the bug**

**To Reproduce**
1. Go to 'Unban players'
2. It doesnt load new banned people, we already banned around 200 players, there is only 8 (So old bans)
[vMenu] [SUCCESS] [BAN] A new ban record has been added. Player: 'Vito Glazov' was banned by 'kFxDaKing' for 'Banned by staff.' until '9/14/2019 10:33:41 PM'.
[vMenu] [ERROR] [DEBUG LOG] SQLite Exception caught: Specified cast is not valid.

- vMenu Version (check the about menu): newest, older 3.0.3 did that too
- Do you have access to the files? yes
- FXServer artifacts version: newest

**Comment by TomGrobbe** [comment]
Use the bans.json instead of SQLite. SQLite is buggy af especially (but not solely) on linux servers.

**Comment by wolgix** [comment]
I have windows server, when i open vmenu_bans there is all bans, but they dont load in game.
Where i can swap to bans.json?

**Comment by TomGrobbe** [comment]
@wolgix there's a convar option for it, read the permissions.cfg/docs

**Comment by wolgix** [comment]
yup got it, can i transfer bans from vmenu_bans.db to bans.json?
Do i need to create bans.json manualy im main folder with server.cfg?

**Comment by TomGrobbe** [comment]
@wolgix The bans.json file is automatically created. You can’t transfer bans from the db file but from the sound of it your majority of banned players is already in the bans.json file, because you said there’s only 8 listed in the sql file

**Comment by wolgix** [comment]
Changed it to false, and it still keep creating vmenu_bans.db ...
