### ISSUE TITLE
VMenu was updated and now Perms no longer work

### ISSUE THREAD

**Issue by DylanfromIUOE** [TomGrobbe/vMenu#217]
Hi, My dev recently updated the vMenu, a day after updating the permissions no longer work.
He supposedly rolled back the version, but still we have the same issue, I asked another dev that uses vMenu about the issue and he stated I needed to stop each script until I found what conflicted. I stopped all resources but the default ones and vMenu with no luck.  

- Server ip: 107.172.196.105:30120
- vMenu Version: 3.0.3 (was supposedly rolled back)
- Do you have access to the files? Yes
- FXServer artifacts version: Unsure, if you have instructions on how to find that out I can.

**Comment by TomGrobbe** [comment]
you're probably just not even executing the permissions.cfg or have the filepath incorrectly configured, or some other typo somewhere. "a day after updating" permissions don't just randomly stop working "a day after". You definitely did something wrong and it has 0 to do with the new update. docs.vespura.com/vmenu has all the info you need to debug the issues. go have a read there.
