### ISSUE TITLE
Streaming Ped's and addon vehicles

### ISSUE THREAD

**Issue by crixzgamez** [TomGrobbe/vMenu#218]
Hello, I didnt want to make a bug report but I wanted to ask you this:
Ive got my custom vehicles and peds located in: 
/server-data/resources/assets/stream/peds/Leo.ytd
/server-data/resources/assets/stream/civilianvehicles/dominator.ytd
The addon vehicle works ingame, not sure about the ped skin, but
I was wondering how I could add these to the vMenu so I can make them work through the "addon vehicle" spawner in vMenu.
Ive tried changing the names in the addons.json to the corresponding of the streamed models.
But it still shows up in gray with a lock symbol.
How and where do I need to edit to make these skins work?
I have not changed my resource_ file.

**Comment by TomGrobbe** [comment]
@crixzgamez The locked item has a description, that tells you exactly the reason why it isn’t working.
