### ISSUE TITLE
vMenu hitches

### ISSUE THREAD

**Issue by wolgix** [TomGrobbe/vMenu#219]
Used this - https://forum.fivem.net/t/how-to-use-the-profiler-command-to-identify-problematic-scripts/809058

And vMenu has biggest hitches.

**Comment by wolgix** [comment]
https://prnt.sc/pcmt0z
https://prnt.sc/pcmt8p
https://prnt.sc/pcmtdn

please how to fix?

**Comment by Zeemahh** [comment]
> vMenu has biggest hitches

Are you just going to ignore that

**Comment by wolgix** [comment]
Its already fixed :)
Now i need to fix the instance + vMenu

**Comment by TomGrobbe** [comment]
@wolgix That doesn’t look like vMenu has the “biggest” hitches. Seems to me that 0.8% is waaaaaay lower than 7.6% from your esx script. Also, the 0.5ms on the client is absolutely nothing for this big of a resource. It’s great performance.
