### ISSUE TITLE
My friend cant see/spawn custom cars using vMenu

### ISSUE THREAD

**Issue by Victor12345nj** [TomGrobbe/vMenu#221]
Hey. I have created a basic FiveM server and added vMenu and an addon car, and then port forwarded it, so my friend can join. But when i spawn the car via "Spawn vehicle by name", my friend cant see me or the car, but i can see and drive the car normally. He have tried spawning the car too via "Spawn vehicle by name" but when he does that, nothing happens. How to fix this?

**Comment by TomGrobbe** [comment]
That's not a vMenu issue. That's an issue with the vehicle model itself.
