### ISSUE TITLE
"vMenu is set up to ignore Permissions"

### ISSUE THREAD

**Issue by Lennoloso** [TomGrobbe/vMenu#297]
**Describe the bug**
Everything is set up correctly in the server.cfg but it says "vMenu is set up to ignore permissions"

**Screenshots**
![image](https://user-images.githubusercontent.com/70822104/231329705-032f3c40-6ff5-4d28-bad1-00b9987c278f.png)
![image](https://user-images.githubusercontent.com/70822104/231329880-1889967a-13f8-4de3-b2b4-72a4132d01ed.png)
![image](https://user-images.githubusercontent.com/70822104/231329970-4199cab2-7d36-4bd6-87be-c8c8895c035b.png) - server.cfg

**vMenu Info**:
- Server ip: 194.156.88.16:30106
- vMenu Version (check the about menu): v.3.5.0
- Do you have access to the files?: yes
- FXServer artifacts version: 6382

**Comment by donjerry4** [comment]
how did u fix this???

**Comment by Bohemeth** [comment]
> how did u fix this???

https://docs.vespura.com/vmenu/installation/   please refer to this link, you have to set your permissions configuration to your liking and then go into server.cfg and above "start vMenu" you type in another line, make sure it is above it. Type a new line "exec @vMenu/config/permissions.cfg"
