### ISSUE TITLE
Help to remove the misc section because civilians can tp everywhere -_-

### ISSUE THREAD

**Issue by z-t3am** [TomGrobbe/vMenu#298]
Please post feature requests in [this](https://github.com/TomGrobbe/vMenu/issues/115) issue instead of creating a new issue for it.

Any requests _not_ posted in that linked issue (#115) may result in you getting banned from this repository.

**Comment by XdGoldenTigerOfficial** [comment]
Permission issue. Dont allow everyone to TP in the permissions.cfg. Closing this as there is nothing we need to fix/update.
