### ISSUE TITLE
vMenu Permission Issue

### ISSUE THREAD

**Issue by milliondollalic** [TomGrobbe/vMenu#301]
I am experiencing an issue assigning admin to a specific individual. This is the only person experiencing this issue which is why I have kind of hit a brick wall and I am now seeking some sort of help. For context, I have put this person's HEX and identifier under group.admin just like all the others, but when he connects he is not able to access player-related options, vehicle-related options, or even see the misc. options tab, however, he can navigate through online players and execute kick, ban, spectate, etc. Again, he is the only one going through this issue. I am very lost and unsure what I could do to resolve this, if anyone could help that would be very nice.
![image](https://user-images.githubusercontent.com/109930107/234493774-56e9323b-8ca4-4717-9b2b-acc18d738cd4.png)
This is the affected user, as you can see, no errors in the code. Which is why I am so confused, I even tried launching with every identifier added, xbl, live, discord, etc. but still that did not resolve the issue. The HEX and identifier is 100% correct.

**Comment by Drift91** [comment]
Sounds like they're not part of the `builtin.everyone` principal for some reason. Would need to see your vMenu `permissions.cfg` and maybe the output of `list_principals` and `list_aces` or any other ace perms you have set up to have a chance of diagnosing it.

**Comment by milliondollalic** [comment]
Hello, its been a while sorry but here is the cfg. Issue persists. How can I provide the file? Cannot upload it.

**Comment by Drift91** [comment]
@milliondollalic Sorry for not getting back to you sooner, you should be able to upload the config on [Pastebin](https://pastebin.com/).

Also something else I thought of, has this user tried clearing their FiveM cache? It's maybe possible that vMenu is corrupted on their end or something. Have you also tried using vMenu to print their identifiers, to make sure they're being recognized by their client and the server?
