### ISSUE TITLE
How can i merge vmenu skins etc

### ISSUE THREAD

**Issue by Avdhjjndrtbb** [TomGrobbe/vMenu#308]
How can i merge vmenu skins etc with kvs files

**Comment by XdGoldenTigerOfficial** [comment]
Could you elaborate more on this?
I am not too sure what you mean by that.

**Comment by XdGoldenTigerOfficial** [comment]
Closed due to inactivity. Please create a new issue if you still have questions about this.
Please be more descriptive next time.
