### ISSUE TITLE
Mod Menu not opening

### ISSUE THREAD

**Issue by riotxxyz** [TomGrobbe/vMenu#311]
EDIT: I HAVE FIXED IT YOU HAVE TO HAVE THIS CODE IN UR SERVER.CFG: 
sv_enforceGameBuild 2944 #mp2023_01 - San Andreas Mercenaries

**Describe the bug**
whenever i get into a vehicle and try to mod it ( changing the colour works fine) when i click mod menu in vehicle options nothing happens, ive installed vMenu a couple of times before following tutorials from the docs.vespura.com and from the youtuber "
HighwayTrooper" and the mod menu option worked back then ( still on the same version)

**To Reproduce**
1. Go to Vehicle related options
2. Click on 'vehicle options'
3. Click on 'Mod Menu'

**Expected behavior**
the mod menu to show up and let me customize 

**Screenshots**
video:https://streamable.com/ntmwqo
screenshot of the console below

**vMenu Info**:
- Server ip: idk what this means u want to connect to my server?  https://cfx.re/join/bblx4d
- vMenu Version (check the about menu): V3.6.0
- Do you have access to the files? yes im the owner
- FXServer artifacts version: Version: FXServer-master v1.0.0.6645 linux, txAdmin Version: 6.0.2 ( i hope this is what u mean)

**Additional context**
Such as:

All permissions havent been changed from default 

I AM USING rocketnode.com AS HOSTING
![image](https://github.com/TomGrobbe/vMenu/assets/143452530/5a2b416b-8815-4cf8-883a-94139e631597)

**Comment by ramonvega2400** [comment]
I am having this same issue. Here is the clientside error.
![image](https://github.com/TomGrobbe/vMenu/assets/92761498/787f36dc-fadc-49c9-87a6-279a908e56a1)

**Comment by riotxxyz** [comment]
> I am having this same issue. Here is the client side console error. ![image](https://user-images.githubusercontent.com/92761498/263842511-787f36dc-fadc-49c9-87a6-279a908e56a1.png)

@ramonvega2400  how do u bring that console thing ingame? i most likely would have the same error

i just find it strange it worked perfectly fine when i self hosted and i even had it working on rocketnode 4 times from previous installations ( vmenu was the same version throughout all)

**Comment by riotxxyz** [comment]
> **Describe the bug** whenever i get into a vehicle and try to mod it ( changing the colour works fine) when i click mod menu in vehicle options nothing happens, ive installed vMenu a couple of times before following tutorials from the docs.vespura.com and from the youtuber " HighwayTrooper" and the mod menu option worked back then ( still on the same version)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to Vehicle related options
> 2. Click on 'vehicle options'
> 3. Click on 'Mod Menu'
> 4. See error
> 
> **Expected behavior** the mod menu to show up and let me customize
> 
> **Screenshots** video:https://streamable.com/ntmwqo
> 
> **vMenu Info**:
> 
> * Server ip: idk what this means u want to connect to my server?  https://cfx.re/join/bblx4d
> * vMenu Version (check the about menu): V3.6.0
> * Do you have access to the files? yes im the owner
> * FXServer artifacts version: Version: FXServer-master v1.0.0.6645 linux, txAdmin Version: 6.0.2 ( i hope this is what u mean)
> 
> **Additional context** Add any other context about the problem here. Such as:
> 
> All permissions havent been changed from default
> 
> I AM USING rocketnode.com AS HOSTING


here is a screenshot of the console
![image](https://github.com/TomGrobbe/vMenu/assets/143452530/6c6e359a-d0f8-44ba-b4d8-eb75c46f4dce)

**Comment by riotxxyz** [comment]
hi, i have started a server and installed vmenu on SELF Hosting and it works , all cars can be spawned in and the mod menu option works, its a server hosting issue, not necessarily a vMenu issue

**Comment by ramonvega2400** [comment]
Not necessarily true, I am using a SELF hosting. There is some bug.

**Comment by riotxxyz** [comment]
> Not necessarily true, I am using a SELF hosting. There is some bug.
put this code into ur server.cfg and make sure your permissions file is in the directory of your server.cfg and make sure exec permissions.cfg is in ur server.cfg ABOVE ensure vMenu


sv_enforceGameBuild 2944 #mp2023_01 - San Andreas Mercenaries

put that above exec permissions.cfg

everything should work including all cars from all DLCS and Mod menu option in vMenu
