### ISSUE TITLE
Spectating should automatically exit on death only when using the built-in function

### ISSUE THREAD

**Issue by DatGuy1** [TomGrobbe/vMenu#312]
I'd like to allow spectating while dead in another script, but https://github.com/TomGrobbe/vMenu/blob/f2daf437267d24a1ebfd3538451a31a2fe5db67b/vMenu/FunctionsController.cs#L1448-L1472 is blocking. There's no real reason to force users to exit spectating while dead, as it still works (especially when spawnmanager's autospawn is disabled)

**Comment by ramonvega2400** [comment]
private async Task SpectateHandling() is not what you should be looking at. You should be looking at the function for Spectate which is in CommonFunctions.cs

**Comment by DatGuy1** [comment]
No. Spectate in CommonFunctions.cs is what's triggered when you press 'spectate player' through online players. The snippet above runs every tick and exits spectating if the player is dead.

This could be easily solved by exposing currentlySpectatingPlayer in CommonFunctions.cs and checking it here, but it's also a question of design that's up to TomGrobbe.
