### ISSUE TITLE
Spectate function causes an infinite black loading screen

### ISSUE THREAD

**Issue by lama-development** [TomGrobbe/vMenu#313]
**Describe the bug**
When attempting to use the spectate function on a player in vMenu, SOMETIMES it results in an infinite black loading screen. Not all of the times, more like 50% of the times.

**To Reproduce**
1. Open vMenu
2. Click on "Online Players"
3. Select a player
4. Click on "Spectate"
5. Most of the times, a black loading screen will appear

**Expected behavior**
I expected to be able to spectate other players without any issues, and the game should not enter an infinite loading screen.

**vMenu Info**:
- vMenu Version (check the about menu): v3.6.0
- Do you have access to the files? Yes
- FXServer artifacts version: Latest Recommended

**Comment by RickyB505** [comment]
that would be because thats how onesync works the code needs to be rewritten to work with onesync

**Comment by lama-development** [comment]
well that sucks

**Comment by XdGoldenTigerOfficial** [comment]
Yeah, in 3.5.0 it worked perfectly fine. I will have a look at the comparison and see what was changed with the spectate function

**Comment by XdGoldenTigerOfficial** [comment]
This should be fixed on the latest release (or pre-release), Reply to this message if it works or if it still doesnt work.
Going to keep this issue open for now.

**Comment by lama-development** [comment]
Thanks! Unfortunately, I don’t have the ability to test it at this time, so I guess you can just close the issue and see if it still gets reported.

**Comment by PassiveRolePlayer** [comment]
yeah it would be great if vMenu could work with on sync infinity, especially the player icons
