### ISSUE TITLE
when I go to vehicle mods, it doesnt let me enter it

### ISSUE THREAD

**Issue by corpzlmao** [TomGrobbe/vMenu#314]
I check the permissions and it says: add_ace builtin.everyone "vMenu.VehicleOptions.Mod" allow
so it should be working, but it doesnt work for anyone else in the server, I click enter on the option and it doesnt do anything, no sound, and no change in the menu

**Comment by RickyB505** [comment]
are you in a vehicle (just making sure)

**Comment by corpzlmao** [comment]
yeah I am lol

**Comment by Gravxd** [comment]
Do you see any errors pop up? Any errors or information in your F8 console that may be of use?

**Comment by corpzlmao** [comment]
![image](https://github.com/TomGrobbe/vMenu/assets/141170030/8b5cdc03-7c9c-43e8-84b3-b3879bd12749)

**Comment by RickyB505** [comment]
make sure your server is set to v2372

**Comment by corpzlmao** [comment]
do u mean the server version? https://runtime.fivem.net/artifacts/fivem/build_client/master/ this thing?

**Comment by RickyB505** [comment]
game build

**Comment by RickyB505** [comment]
https://docs.fivem.net/docs/server-manual/server-commands/#sv_enforcegamebuild-build

**Comment by corpzlmao** [comment]
that works, but them my eup crashes my game, and when I change it back to the original build, the eup works, but the vehicle mod menu doesnt,

**Comment by RickyB505** [comment]
cant help you with EUP not my area of expertise

**Comment by corpzlmao** [comment]
Its not an EUP problem, since it works when its not that version but doesnt work when it is that version, and the vmenu works when it is that version, but not any other version

**Comment by corpzlmao** [comment]
I fixed it, thanks, and another problem I have is the world options, when I try and change the weather/time it tells me its gonna change but it doesnt change

**Comment by RickyB505** [comment]
did you disable vmenu_enable_weather_sync, vmenu_enable_time_sync if so thats probably why

**Comment by corpzlmao** [comment]
No its enabled, and it still doesnt work

**Comment by ihavetourettes** [comment]
Any fix to this? I am having the same problem Mods for vehicles no longer opens.

**Comment by XdGoldenTigerOfficial** [comment]
If you are running on an older game build (not the latest), the mod menu will not work. Some stupid person (me) forgot to add a check to see if they are running the right game build.

The easiest way to fix this is to enforce the latest game build for your server:
https://docs.fivem.net/docs/server-manual/server-commands/#sv_enforcegamebuild-build
`sv_enforceGameBuild 2944`

I will be working on a fix for it when I get time.

**Comment by xCashz** [comment]
@XdGoldenTigerOfficial Any update?

**Comment by Mr-Chris-VRTY** [comment]
> If you are running on an older game build (not the latest), the mod menu will not work. Some stupid person (me) forgot to add a check to see if they are running the right game build.
> 
> The easiest way to fix this is to enforce the latest game build for your server: https://docs.fivem.net/docs/server-manual/server-commands/#sv_enforcegamebuild-build `sv_enforceGameBuild 2944`
> 
> I will be working on a fix for it when I get time.

Still no fix?

**Comment by XdGoldenTigerOfficial** [comment]
> > If you are running on an older game build (not the latest), the mod menu will not work. Some stupid person (me) forgot to add a check to see if they are running the right game build.
> > The easiest way to fix this is to enforce the latest game build for your server: https://docs.fivem.net/docs/server-manual/server-commands/#sv_enforcegamebuild-build `sv_enforceGameBuild 2944`
> > I will be working on a fix for it when I get time.
> 
> Still no fix?

Yes, there is a fix... As I said, enforce the latest game build. That is the best, and more reliable way of doing it.
You get all the new amazing DLC content if you just... ENFORCE THE LATEST GAME BUILD.
Keep your servers, and FiveM up to date on the latest builds for the new content!

**Comment by xCashz** [comment]
He said he'd deploy an actual fix. I'm aware of the game builds but that's
just a temporary fix for me right now.

**Comment by XdGoldenTigerOfficial** [comment]
There will be a fix in the code when I get the time, or when another person can fix it with a PR.
For right now, the best thing to do is to enforce the latest game build, and in my opinion, and most likely everyone elses, enforcing the latest game build is the best thing to do, which keeps everything in-game up to date for ALL players.

**Comment by Mr-Chris-VRTY** [comment]
> > > If you are running on an older game build (not the latest), the mod menu will not work. Some stupid person (me) forgot to add a check to see if they are running the right game build.
> > > The easiest way to fix this is to enforce the latest game build for your server: https://docs.fivem.net/docs/server-manual/server-commands/#sv_enforcegamebuild-build `sv_enforceGameBuild 2944`
> > > I will be working on a fix for it when I get time.
> > 
> > 
> > Still no fix?
> 
> Yes, there is a fix... As I said, enforce the latest game build. That is the best, and more reliable way of doing it. You get all the new amazing DLC content if you just... ENFORCE THE LATEST GAME BUILD. Keep your servers, and FiveM up to date on the latest builds for the new content!

Quiet easy but I use cayo on FiveM Server so I have to use old build haha 
So fix for older versions will be great
