### ISSUE TITLE
vMenu Vehicle Mod Menu Unclickable.

### ISSUE THREAD

**Issue by foslidin** [TomGrobbe/vMenu#364]
**Describe the bug**
In the vMenu when i got to vehicle options, and hover over mod menu, i have the ability to click it and i see the option but when i click it to enter the mod menu, nothing loads. All permissions are set and enabled. It is just this certain one for some reason. 

**To Reproduce**
1. Go to vehicle options menu
2. Click on mod menu 
3. Doesnt load

**Expected behavior**
The vehicle mod menu is suppose to load

**vMenu Info**:
- Server ip: 104.143.3.63:3748
- vMenu Version (3.6)
- Do you have access to the files? Yes
- FXServer artifacts version: latest 

All permissions are allowed for vehicle options

**Comment by pp842** [comment]
Im getting the same issue idk why.

**Comment by RickyB505** [comment]
https://github.com/TomGrobbe/vMenu/issues/314#issuecomment-1812310922
