### ISSUE TITLE
Anyone have a commit they are working on to update to latest game build?

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [TomGrobbe/vMenu#366]
3095 is out now. Anyone know if someone is working on an update for vMenu?

Perhaps @XdGoldenTigerOfficial ?

**Comment by Legacy-TacticalGamingInteractive** [comment]
I noticed there was some commit but it says the build failed and no actual new release so im not sure?

**Comment by XdGoldenTigerOfficial** [comment]
> I noticed there was some commit but it says the build failed and no actual new release so im not sure?

There is a new pre-release with the latest Chop Shop DLC content (v3.6.1-pre)
There is an issue with the default keybindings, you will need to set your vMenu open key in the FiveM keybind settings. (This is currently being worked now)
