### ISSUE TITLE
vMenu GodMode Bug

### ISSUE THREAD

**Issue by seechxn** [TomGrobbe/vMenu#367]
**Describe the bug**
I turned on god mode using vMenu, but invincibility is not activated and I keep dying.

**vMenu Info**:
- Server ip: 95.214.179.32
- vMenu Version (check the about menu): 3.6.0
- Do you have access to the files?
- FXServer artifacts version: 1739

**Comment by XdGoldenTigerOfficial** [comment]
Please elaborate further... Any errors in F8, or server console?

**Comment by ryanb9038** [comment]
Your server likely has an anti-cheat that forces god-mode off for all players. Anti-cheese does this and a few others that I cannot think of. If it is not an anti-cheat, then it is another resource that has the capability to handle invincibility that is conflicting with vMenu.
