### ISSUE TITLE
MP Ped - way to save current ped

### ISSUE THREAD

**Issue by waynieoaks** [TomGrobbe/vMenu#371]
e.g. under Manage Saved Characters the ability to save existing or for saved characters ability to replace (like we can with the saved (non-mp) peds)

**Comment by waynieoaks** [comment]
May not be possible with GTA limitations, sadly

**Comment by XdGoldenTigerOfficial** [comment]
> e.g. under Manage Saved Characters the ability to save existing or for saved characters ability to replace (like we can with the saved (non-mp) peds)

We could add the option for that, I will talk to the other guys and see if they would be interested in adding that in ;-)
