### ISSUE TITLE
vMenu Crashing when joining server 

### ISSUE THREAD

**Issue by toasty4576** [TomGrobbe/vMenu#372]
vMenu Crashing when joining server 

Cant join the server when vMenu is in 

But when vMenu is removed i can join it just fine i don't know what I'm doing wrong here/never had this issue before

**Comment by RickyB505** [comment]
are you using v3.6.0

**Comment by toasty4576** [comment]
Yes i am

**Comment by JackReagan** [comment]
Same thing is happening to me since 2 days any fix or update about that ?
