### ISSUE TITLE
Unable to Add vehicles to Category's + Vmenu dump causing unknown Error

### ISSUE THREAD

**Issue by error-reporter-cmd** [TomGrobbe/vMenu#376]
**Describe the bug**
Unable to Add vehicles to Category's 

**To Reproduce**
1. Go to Saved Vehicles > Vehicle class
2. Click on any category 
3. Scroll down to a vehicle and attempt to cycle to a created catagory
4. See error (`` Failed to run a tick for MenuController: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot apply indexing with [] to an expression of type `null'``

**Expected behavior**
Be able to add vehicle to the category 

**Screenshots**
![image](https://github.com/TomGrobbe/vMenu/assets/80724122/88923fad-2c94-4e12-bc01-0084d226fd51)
![image](https://github.com/TomGrobbe/vMenu/assets/80724122/a44c0692-4386-416b-a364-99fa5830d7a7)

**vMenu Info**:
- vMenu Version (check the about menu):V3.6.2
- Do you have access to the files? Yes
- FXServer artifacts version: "FXServer-master SERVER v1.0.0.7320 win32"

**Additional context**
Such as:
[CitizenFX_log_2024-02-16T234938.log](https://github.com/TomGrobbe/vMenu/files/14316950/CitizenFX_log_2024-02-16T234938.log)

**Comment by Gravxd** [comment]
Experiencing the same issue, was working fine at first with categories then after i created some, it randomly started doing this for multiple of our players.

We're running game build 2699, artifacts: 7406
