### ISSUE TITLE
vMenu won't open at all

### ISSUE THREAD

**Issue by JayH5021** [TomGrobbe/vMenu#379]
**Describe the bug**
Hello, 
Installed the new version of vMenu 3.6.2 and it won't open in-game.
Tried different different things to fix it, like changing game versions... but nothing worked
I have executed the permission.cfg above ensure vMenu in my server.cfg
Permission is in the same place as the server.cfg
Changed the id's to get my steam ID but nothing.

**Expected behavior**
When I install the menu i wanted it to work directly and not having to try to find the issue and can't find a solution at all. 

**Screenshots**
Not possible to have a screenshot showing nothing

**Comment by MaegnusEvermoore** [comment]
I noticed this happened when we updated. noticed that the keybind was unset for some reason after the update, try going into the games settings and check the fivem keybinds

**Comment by ICU2D** [comment]
try doing /vMenu:Default:MenuToggle if resetting the keybind doesn't work

**Comment by gael743** [comment]
When i check the keybinds is just txadmin there not v menu
