### ISSUE TITLE
VMenu blips don't work with OneSync Infinity

### ISSUE THREAD

**Issue by CoolSlayer131** [TomGrobbe/vMenu#380]
**Describe the bug**
Members with Blips toggled on will only see players that are in their immediate area, Being unable to see individuals anywhere else on the map, This causes issues for staff members trying to for example find somebody out of Area of play or flying around (Modding)

**To Reproduce**
1. Go to MISC Settings
2. Click on Show Player Blips
4. See error on world wide map

**Expected behavior**
Seeing all players regardless of where you stand on the map

**Screenshots**
![b6156d62de95b8914db0d46ea465edb2](https://github.com/TomGrobbe/vMenu/assets/61106540/32e83d43-2b7f-44f6-8eac-0d566aa2d7ad)

**vMenu Info**:
- vMenu Version (check the about menu): VMenu 3.6.2
- Do you have access to the files? No
- FXServer artifacts version: 7290

**Additional context**
Such as: N/A

**Comment by Gravxd** [comment]
This isn't a bug, this is how onesync infinity works in FiveM you only render players in your "bubble"
