### ISSUE TITLE
Auto Un-categorizing Replaced Vehicles

### ISSUE THREAD

**Issue by CoolSlayer131** [TomGrobbe/vMenu#387]
**Describe the bug**
Replacing vehicles will un-categorize them, forcing you to go back and re-catagorize, Bad for LEO who need to switch plates a lot to callsigns 

**To Reproduce**
1. Go to 'Saved Vehicles'
2. Click on 'Your category'
3. Scroll down to 'Your vehicle'
4. Click on 'Replace Vehicle'
5. See error by returning to that category, The car is no longer saved in its category 

**Expected behavior**
Vehicles to stay in assigned category and not uncategorize when replacing.

**Screenshots**
N/A

**vMenu Info**:
- vMenu Version (check the about menu):
3.6.2
- Do you have access to the files?
No
- FXServer artifacts version:
7290

- A list of allowed permissions for the player that is having this issue.
All

**Comment by GrandpaRex** [comment]
Can confirm this bug

- vMenu Version (check the about menu):

3.6.2

- Do you have access to the files?
Yes

- FXServer artifacts version:
b7595

- A list of allowed permissions for the player that is having this issue.
All

**Comment by XdGoldenTigerOfficial** [comment]
@cm8263

**Comment by cm8263** [comment]
Yikes, sorry I didn't notice this issue sooner, it's such a simple fix 😭 

Anywho, fixed in #404 👍
