### ISSUE TITLE
[SUGGESTION] Player Blips should work with OneSync Infinity.

### ISSUE THREAD

**Issue by Posh04** [TomGrobbe/vMenu#388]
**Describe the bug**
When your FXServer is on OneSync Infinity Player Blips no longer show on a global scale and instead show people in your immediate area.

If there is a way, we can be able to see Player Blips on a Global Scale again?

**Comment by Gravxd** [comment]
This is not expected behaviour. Onesync infinity renders players in a "bubble" or "scope" around the player, meaning you only load in players in x radius to you. Hence you only can get the blips for nearby players as your client isn't "aware" of all players in the server that are outside the scope.

**Comment by GrandpaRex** [comment]
It is possible it just requires clients to constantly update a server function with their x,y,z,h coords then that server function to pass it to all clients

**Comment by PassiveRolePlayer** [comment]
vMenu should have a on sync compatibly setting or something. everyone is using onesync
