### ISSUE TITLE
[Code Clarification] ShowHeightOnBlip

### ISSUE THREAD

**Issue by GrandpaRex** [TomGrobbe/vMenu#390]
In the FunctionsController.cs in the player blips section [specifically line 2243 in my fork] there is a native that is listed as unknown
`//N_0x75a16c3da34f1245(blip, false); // unknown`

That native comes back to [ShowHeightOnBlip](https://docs.fivem.net/natives/?_0x75A16C3DA34F1245)

Just wanted to pass that along, thanks!

**Comment by Mathu-lmn** [comment]
Thank you, I've updated all the unknown natives in my last PR 👍🏻
