### ISSUE TITLE
Mod Menu Not Working

### ISSUE THREAD

**Issue by Ezer310** [TomGrobbe/vMenu#394]
Hello just want to address an issue involving vmenu I installed the new version of it on my test server but when I try to use the mod menu it doesn't open. Need Help!!

**Comment by YinAndYangWolves** [comment]
> Hello just want to address an issue involving vmenu I installed the new version of it on my test server but when I try to use the mod menu it doesn't open. Need Help!!

Set this in your server.cfg

sv_enforceGameBuild 2944

**Comment by xotiic9933** [comment]
i key mapped my vmenu to open at 244 wich is M but i cant get it to work, any help?

**Comment by hudoghyper** [comment]
> > Hello just want to address an issue involving vmenu I installed the new version of it on my test server but when I try to use the mod menu it doesn't open. Need Help!!
> 
> Set this in your server.cfg
> 
> sv_enforceGameBuild 2944

THANK UUUUU for everyone this is if your Vehicle Related Options > Vehicle Options > Mod Menu wont open

**Comment by Dennis3369** [comment]
I'm having the same issue
