### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by azjoey15** [TomGrobbe/vMenu#396]
![image](https://github.com/TomGrobbe/vMenu/assets/164584163/3f703d2d-98b1-487d-9ef6-9ba3e1019912)

![image](https://github.com/TomGrobbe/vMenu/assets/164584163/6590b6cc-1ff7-431e-98cd-084df47539c5)

not sure the cause of this but i think i messed up the menu

**Comment by TheFaultRoleplay** [comment]
How'd you get the custom image on the blue part?
