### ISSUE TITLE
Addon Vehicle Spawner Not Working

### ISSUE THREAD

**Issue by TheFaultRoleplay** [TomGrobbe/vMenu#397]
**Describe the bug**
This bug is revolving around the Addon Vehicle Spawner menu inside Vmenu. I had inputted all the cars, with the correct spawn codes and everything in the addon.json file, But yet it says "There are no addon vehicles in this server" It seems like im the only one experiencing this issue

**Expected behavior**
I expected to be able to load into game and be able to use the spawn menu to spawn the vehicles instead of having to post spawn-codes for people to use instead.

**Screenshots**

**vMenu Info**:
- Server ip: 185.240.134.92:2006
- vMenu Version (check the about menu): 'v3.6.2'
- Do you have access to the files? Yes
- FXServer artifacts version: 7917

**Additional context**
Such as:

- Everyone is experiencing this issue
- Here's all Vehicle Spawner permissions in the permissions.cfg file in my server
- add_ace builtin.everyone "vMenu.VehicleSpawner.Menu" allow
add_ace builtin.everyone "vMenu.VehicleSpawner.All" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.DisableReplacePrevious" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.SpawnByName" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Addon" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Compacts" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Sedans" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.SUVs" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Coupes" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Muscle" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.SportsClassic" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Sports" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Super" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Motorcycles" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.OffRoad" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Industrial" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Utility" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Vans" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Cycles" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Boats" allow
#add_ace group.admin "vMenu.VehicleSpawner.Helicopters" allow
#add_ace group.admin "vMenu.VehicleSpawner.Planes" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Service" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Emergency" allow
#add_ace group.admin "vMenu.VehicleSpawner.Military" allow
#add_ace builtin.everyone "vMenu.VehicleSpawner.Commercial" allow
#add_ace group.admin "vMenu.VehicleSpawner.Trains" allow
#add_ace group.admin "vMenu.VehicleSpawner.OpenWheel" allow

Both of these can very easily be provided by using `/vmenuclient dump` while in-game and sending the CitizenFX.log file (`FiveM Application Data\CitizenFX.log`) from that same game session.

**Comment by YonLiud** [comment]
I have experienced this issue before, and it's not that complicated to resolve. Ensure that all the vehicle spawn codes in your `addon.json` file are correct. It might seem trivial, but even a single incorrect spawn code can corrupt the entire file. Double-check each code to make sure they are all accurate.

This simple step should resolve the issue.
