### ISSUE TITLE
[SUGGESTION] Stop the global saves

### ISSUE THREAD

**Issue by tannnxr** [TomGrobbe/vMenu#399]
Make it so that vMenu saves outfits and vehicles per server rather than globally.  It just bloats saved outfits if we're in multiple servers.

**Comment by TomGrobbe** [comment]
This will never change. It’s intentionally saved on the client side so it is shared across all servers.

the only thing that we could change about this is adding categories or a folder like functionality. Where you can place saved files inside a specific folder. But only if @XdGoldenTigerOfficial feels like adding that.

**Comment by tannnxr** [comment]
Folders/Directories would seriously help.  +1 for this
