### ISSUE TITLE
vMenu not working past X: 16000 Y: 16000 Coordinates 

### ISSUE THREAD

**Issue by NunoSz** [TomGrobbe/vMenu#402]
After converting an SP Beta map that is outside bounderies i installed https://github.com/iModyHK/limits which is a conversion of the SP mod, the map shows up and is completly fine, however if i try spawning vehicles there, i can't, if i try no cliping, i'm able to go into the mode but cannot move. After trying to fly there i cant get past 16k 16k coordinates, seems to be an invisible wall. Every other option seems to work just fine, i also cant teleport there with the teleport to coordinate nor can i tp to a saved place there. 

**To Reproduce**
1. Install outside bounderies map
2. install https://github.com/iModyHK/limits
3. Try to fly there with noclip(you will run into the wall)
4. Fly with a plane and try to use vMenu there.

**Expected behavior**
Be able to use the Menu as in the San Andreas area.

**Screenshots**
![image](https://github.com/TomGrobbe/vMenu/assets/173554384/2e853bc7-6292-46b5-ada7-03941e194d4a)

**vMenu Info**:
- Server ip: Private
- vMenu Version (check the about menu): 3.5.0(Dosent work on latest either)
- Do you have access to the files? Yes
- FXServer artifacts version: 7999
 {"vmenu_use_permissions":"true","vmenu_menu_staff_only":"false","vmenu_menu_toggle_key":"288","vmenu_noclip_toggle_key":"289","vmenu_keep_spawned_vehicles_persistent":"false","vmenu_use_els_compatibility_mode":"false","vmenu_handle_invisibility":"true","vmenu_quit_session_in_rockstar_editor":"false","vmenu_server_info_message":"About this server, discord: vespura.com/discord","vmenu_server_info_website_url":"www.vespura.com","vmenu_teleport_to_wp_keybind_key":"168","vmenu_disable_spawning_as_default_character":"false","vmenu_enable_animals_spawn_menu":"false","vmenu_pvp_mode":"1","vmenu_disable_server_info_convars":"false","vmenu_player_names_distance":"500.0","vmenu_disable_entity_outlines_tool":"false","vmenu_disable_player_stats_setup":"false","vmenu_default_ban_message_information":"Please contact the staff team by going to (support url) if you want to appeal this ban","vmenu_auto_ban_cheaters":"false","vmenu_auto_ban_cheaters_ban_message":"You have been automatically banned. If you believe this was done by error, please contact the server owner for support.","vmenu_log_ban_actions":"true","vmenu_log_kick_actions":"true","vmenu_enable_weather_sync":"true","vmenu_enable_dynamic_weather":"true","vmenu_dynamic_weather_timer":"15","vmenu_current_weather":"clear","vmenu_blackout_enabled":"false","vmenu_weather_change_duration":"30","vmenu_enable_snow":"false","vmenu_enable_time_sync":"true","vmenu_freeze_time":"false","vmenu_ingame_minute_duration":"2000","vmenu_current_hour":"11","vmenu_current_minute":"11","vmenu_sync_to_machine_time":"false"}

**Comment by NunoSz** [comment]
Also, spawning outside the vehicle dosent work either, both time all you get is this in console 
![image](https://github.com/TomGrobbe/vMenu/assets/173554384/302e2414-7141-4b80-b416-385cbbc57840)

**Comment by YonLiud** [comment]
It appears that this issue is not related to vMenu. According to observations, all entities beyond `X = ±8000` and `Y = ±8000` are automatically destroyed by GTA V's engine upon spawning. This explains why attempting to open vMenu and spawn vehicles beyond these coordinates fails—they are immediately deleted by the engine upon spawn. 

To verify this behavior, you can noclip to coordinates `X = 15999` and `Y = 15999` and attempt to spawn a boat or submarine, which will demonstrate that they are destroyed and uncontrollable.

**Comment by NunoSz** [comment]
It's important to remember i have that boundary limits script which removes the default game boundary limits, or better, extends them. From what i could test, I can get vehicles past X=±16000  Y=±16000 with no problems, be it a boat, a plane, a car or even a submarine. However, vMenu does not work past X=±15999 Y=±15999, I cannot noClip(I can go into noClip but i cannot move), i cannot spawn vehicles and many other issues.
If I remove said boundary scripts, it is like you said, Past X=±8000 Y=±8000 the vehicle engine is killed. However, if i keep flying with noClip, which I'm able to, I run into the previous 'wall' in X=±16000  Y=±16000.
