### ISSUE TITLE
Vehicle is being streamed correctly

### ISSUE THREAD

**Issue by N0T0RIOUSS** [TomGrobbe/vMenu#405]
This vehicle is not available. Please ask the server owner to check if the vehicle is being streamed correctly. I followed every step of the youtube videos and it still says this

**Comment by N0T0RIOUSS** [comment]
![Screenshot 2024-06-30 192634](https://github.com/TomGrobbe/vMenu/assets/145226597/6518cf1c-3ab8-4320-9a19-c579ac490279)

**Comment by Mathu-lmn** [comment]
This simply checks this native : IsModelInCdimage
Have you correctly entered the vehicle's model, are you able to spawn it with an external resource ?

**Comment by kadins1** [comment]
Been deving with vMenu for about 4 years, never had this issue, I'd go back and rewatch the tutorial. If that doesn't work watch another one.
