### ISSUE TITLE
[Suggestion] Add new license plate types to vMenu vehicle options

### ISSUE THREAD

**Issue by MichaelCoding25** [TomGrobbe/vMenu#407]
vMenu only has the base 5 license plate types to choose from.
the game itself, especially with the new dlcs has a much bigger variety so I think adding them is a good idea.
Here is a link to an update that was made to the fivem natives that specifies the new types: https://github.com/citizenfx/natives/commit/ada4c422d7902527469621199b53c8a5b5841537

**Comment by XdGoldenTigerOfficial** [comment]
Sweet, I will have a look 😉

**Comment by Legacy-TacticalGamingInteractive** [comment]
https://forum.cfx.re/t/free-custom-license-plates-and-patterns/4777586/164

thats some of the new plates, in case you are curious @XdGoldenTigerOfficial

**Comment by XdGoldenTigerOfficial** [comment]
The natives docs had been updated, but not the C# package.
So I created a pull request on the fivem repo yesterday, awaiting them to merge this.
https://github.com/citizenfx/fivem/pull/2818

Once merged, I should be able to add the new plates in ;-)

**Comment by XdGoldenTigerOfficial** [comment]
Perfect, it has been merged.
I will get started on adding these in once the Nuget package gets released 😉

**Comment by XdGoldenTigerOfficial** [comment]
Disregard that last part of that message. Forgot FiveM is so advanced it automatically builds the latest merges 😂 
Added the new plates into vMenu, tested it and they all work.

Will update the vMenu repo very soon

**Comment by XdGoldenTigerOfficial** [comment]
https://cdn.discordapp.com/attachments/648513027683123213/1291416165763125299/2024-10-04_03-58-40.mp4

**Comment by XdGoldenTigerOfficial** [comment]
#452
