### ISSUE TITLE
[Suggestion] Allow Addon Weapons to use Weapon Options Menu

### ISSUE THREAD

**Issue by blackfirefly000** [TomGrobbe/vMenu#418]
Right now, addon weapons added with the addons.json cannot use the Weapon Options menu to change tints, add components, refill ammo, etc. This means that addon weapons need to be added into the main build in the ValidWeapons.cs to use these features. This will cause conflicts when trying to update vMenu and can cause issues if someone doesn't know what they're doing.

**Comment by kadins1** [comment]
With you on this one, I've felt the pain of this before.
