### ISSUE TITLE
Xmas Snow is crashing everyone

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [TomGrobbe/vMenu#422]
![image](https://github.com/user-attachments/assets/dfe6e30c-d530-4e71-9aee-c8ad3221a3e6)

Entire server crashed when we turned on "Xmas Snow" setting in vMenu. Have to say its the first time we've ever seen the weather cause crashes.

Has this native been changed recently?

tx: v7.2.2 | fx: b9424
vMenu v3.6.3

Oh?
![image](https://github.com/user-attachments/assets/fc42a8cb-56c7-4cab-8fa6-95b6d5fea2a3)

**Comment by Mathu-lmn** [comment]
I just noticed the same thing, will take a deeper look now

**Comment by Mathu-lmn** [comment]
Also, the link is malformed, but the file exists : https://sourcegraph.com/github.com/citizenfx/fivem@master/-/blob/code/components/extra-natives-five/src/WeatherNatives.cpp?L70%3A29-70%3A49=

**Comment by Mathu-lmn** [comment]
https://github.com/citizenfx/fivem/issues/2736
I have created an issue related to your issue on the FiveM's github

**Comment by Legacy-TacticalGamingInteractive** [comment]
Looks like someone has made a PR and its being worked on.
Due to new weather type called XMAS_HALLOWEEN being added in 3095.

https://github.com/citizenfx/fivem/pull/2743

**Comment by Legacy-TacticalGamingInteractive** [comment]
They say its been fixed. I haven't tested myself yet but assuming we are good to close.
