### ISSUE TITLE
Problem tuning vehicle

### ISSUE THREAD

**Issue by PazuzuBr** [TomGrobbe/vMenu#423]
I can spawn the vehicles all right, but the modmenu option to tune it doesn't work, I click and nothing happens, it doesn't open the options to modify the car parts.

**Comment by Mathu-lmn** [comment]
Hi, could you send a video about this please

**Comment by Mathu-lmn** [comment]
What gamebuild are you on ? You might need to be above b2372

**Comment by Mathu-lmn** [comment]
I made a PR to fix this issue

**Comment by PazuzuBr** [comment]
> What gamebuild are you on ? You might need to be above b2372

I always use the newest build, so do I get the oldest b2372 from 2020?

**Comment by Mathu-lmn** [comment]
I didn't mean artifacts, I meant game build aka GTA DLC

**Comment by PazuzuBr** [comment]
> I didn't mean artifacts, I meant game build aka GTA DLC

![image](https://github.com/user-attachments/assets/191dfe7d-9e9a-4004-aea4-c7b8f1c64e32)

**Comment by Mathu-lmn** [comment]
Yes please check the number that's shown in a corner of the screen, it should say b with 4 numbers

**Comment by PazuzuBr** [comment]
> Yes please check the number that's shown in a corner of the screen, it should say b with 4 numbers

I did it, thank you very much friend, you saved me

**Comment by cauamv** [comment]
> > Yes please check the number that's shown in a corner of the screen, it should say b with 4 numbers
> 
> I did it, thank you very much friend, you saved me

What did you do to fix this?

**Comment by Mathu-lmn** [comment]
Switch to a build after 2372

**Comment by cauamv** [comment]
> Switch to a build after 2372

Which build do you recommend? I have a server with just vMenu with my friends, nothing special

**Comment by Mathu-lmn** [comment]
I'd recommend 3095, it's the latest stable

**Comment by cauamv** [comment]
![image](https://github.com/user-attachments/assets/6fad2353-957e-4dcd-9393-981fecd4e9ee)
I added this to my config file, is that right?

**Comment by Mathu-lmn** [comment]
Yes it is right
