### ISSUE TITLE
Adding addon components to addons.json breaks vMenu

### ISSUE THREAD

**Issue by blackfirefly000** [TomGrobbe/vMenu#431]
**Describe the bug**
Adding addon components to addons.json breaks vMenu

**To Reproduce**
1. Go to 'addons.json'
2. Add any weapon component
3. Load vMenu

```SCRIPT ERROR in task continuation: System.NullReferenceException: Object reference not set to an instance of an `object`
void vMenuClient.data.ValidAddonWeapons.CreateAddonWeaponsList() (@vMenu/vMenuClient.net.dll:0)
List<ValidAddonWeapon> vMenuClient.data.ValidAddonWeapons.get_AddonWeaponsList()(@vMenu/vMenuClient.net.dll:0)
void vMenuClient.menus.WeaponOptions.CreateMenu() (@vMenu/vMenuClient.net.dll:0)
Menu vMenuClient.menus.WeaponOptions.GetMenu() (@vMenu/vMenuClient.net.dll:0)
void vMenuClient.MainMenu.CreateSubmenus() (@vMenu/vMenuClient.net.dll:0)
void vMenuClient.MainMenu.PostPermissionsSetup() (@vMenu/vMenuClient.net.dll:0)
async void vMenuClient.MainMenu.SetPermissions(string permissionsList) (@vMenu/vMenuClient.net.dll:0)```

**Expected behavior**
Addon components are usable on whichever weapon is set up to equip them

**Screenshots**
![image](https://github.com/user-attachments/assets/cfc17a42-86de-4e53-9592-14c120af415f)

**vMenu Info**:
- vMenu Version (check the about menu): 3.6.4pre
- Do you have access to the files? yes
- FXServer artifacts version: b9875

**Comment by SkylarPlayz348** [comment]
The addon weapon system is broken currently. The only way to add custom weapons / weapon components is to edit the source code

**Comment by blackfirefly000** [comment]
> The addon weapon system is broken currently. The only way to add custom weapons / weapon components is to edit the source code

It’s not completely broken. You can add weapons but they will not have useable components. I’m working on an update to the addon weapons menu but I made this bug report in case anyone has a fix for this code which predates and changes I’ve made.

**Comment by blackfirefly000** [comment]
Fixed in https://github.com/TomGrobbe/vMenu/pull/428
