### ISSUE TITLE
vmenu isnt in my consol

### ISSUE THREAD

**Issue by bojko1659** [TomGrobbe/vMenu#433]
hello
when i open my consol for my server the vmenu doesnt show up and it doesnt work i putted the vmenu in my resources in a new folder and put the permission file in the first folder
![image](https://github.com/user-attachments/assets/4306c857-d15d-4815-a08b-20ee9db29e35)

**Comment by XdGoldenTigerOfficial** [comment]
Maybe check out a basic tutorial on how to run a FiveM server before making an issue on an external FiveM resource.
