### ISSUE TITLE
Track wheels again. 

### ISSUE THREAD

**Issue by Fyreside** [TomGrobbe/vMenu#447]
Hi,  quite a few versions ago I was able to access the track wheels category.   I can see the old commit from when it was added, but Haven't been able to access track wheels for a few versions now. Just wondering if this is a known issue and if we might have them back please.     It's wheel category 12 from the Tuners DLC in 2021.

**Comment by Fyreside** [comment]
I don't know how best to be helpful with this, but I had a look through and this appears to be where it changed. Unable to see why it might have been removed. 
 https://github.com/TomGrobbe/vMenu/commit/be1ba1267f3a021843680bbb3b1126beed566851

**Comment by XdGoldenTigerOfficial** [comment]
I am not too sure how that was removed. I dont remember touching anything to do with the wheels.
A PR has been merged to fix this issue
