### ISSUE TITLE
Time Rapidly Changing

### ISSUE THREAD

**Issue by XxROBOTICSxX** [TomGrobbe/vMenu#64]
While using the addon the time rapidly changes between noon and the server time. This may be a conflict with the time synchronization addon we use on our server, just thought I should report this issue. It only occurs while vMenu is running.

**Comment by TomGrobbe** [comment]
This is indeed caused by a conflict between this resource and your other time sync resource. You can disable time and weather sync in this menu by adding `set vMenuDisableTimeAndWeatherSync "true"` to the very top of your server.cfg.
Or remove the other time/weather sync script.
