### ISSUE TITLE
Some multiplayer model components not saving

### ISSUE THREAD

**Issue by jellyton69** [TomGrobbe/vMenu#71]
When saving a multiplayer model that was edited using the simple trainer or skin control script it appears that not all modifications to the model are saved. Some things like skin color, hair color, tattoos, etc, aren't brought back when loading your saved model.

Additionally, a suggestion for a future update would be to add full support for Multiplayer Model configuration.

Edit: If you feel like getting really in-depth with it; if you have ever used the EUP menu, there is a really cool and extensive customization tool that takes advantage of some of the features of the NativeUI.

Simple Trainer:
![](https://i.imgur.com/xjRPjzM.png)

vMenu:
![](https://i.imgur.com/VNx5Hmz.png)

**Comment by TomGrobbe** [comment]
This is intended behavior as there's no customization or support for mp models. Might add this in a future update.
