### ISSUE TITLE
Can't join server

### ISSUE THREAD

**Issue by Halotacos** [TomGrobbe/vMenu#72]
So I followed the install readme and made sure to add the exec permissions.cfg to my server.cfg and copied over the permissions.cfg into the folder but when I try and join my server I get this error "Failed handshake to server 67.3.10.9:30120 - Failed to connect to 67.3.10.9 port 30120: Timed out - CURL error code 7 (Couldn't connect to server)."
![capture](https://user-images.githubusercontent.com/15131166/37938189-9b136cc0-3122-11e8-8226-e781396dc16c.PNG)
![capture](https://user-images.githubusercontent.com/15131166/37938198-ae1e0b90-3122-11e8-9e42-90364558a0c0.PNG)
![capture](https://user-images.githubusercontent.com/15131166/37938301-bf64cc7c-3122-11e8-9e91-66ad8054f8df.PNG)
![capture](https://user-images.githubusercontent.com/15131166/37938310-c98d8806-3122-11e8-9310-7293398e0c5b.PNG)

**Comment by TomGrobbe** [comment]
This is not related to vMenu. This is because you haven't setup your server correctly, for support on setting up your server take a look at the FiveM wiki page or go to forum.fivem.net and ask for support there please.

**Comment by Halotacos** [comment]
It only happens when I user vMenu

**Comment by TomGrobbe** [comment]
Any repro steps that I can try to recreate this?

**Comment by Halotacos** [comment]
I can send you the files if you want

**Comment by TomGrobbe** [comment]
What server artifacts version are you using? And you _are_ able to connect if you disable vMenu?

**Comment by Halotacos** [comment]
558-deb66d570b3e57159522ff3323bb3e3b80af1a3d/   and yes

**Comment by TomGrobbe** [comment]
Is this using linux or windows as server host?

**Comment by Halotacos** [comment]
Windows

**Comment by TomGrobbe** [comment]
Just tested it and it works fine for me on the same build...

**Comment by Halotacos** [comment]
strange

**Comment by Halotacos** [comment]
It works if I use direct cnnect

**Comment by TomGrobbe** [comment]
If you use direct connect with your local IP or from an external IP? Seems like a firewall/port forward issue in that case.

**Comment by Halotacos** [comment]
external IP and I have port forwarded my server and allow it to access every network

**Comment by Halotacos** [comment]
so I was not using an external IP, and I have tried making sure the firewall allows the ports and I made sure to port forward 30110-30120,
