### ISSUE TITLE
Overriding other script

### ISSUE THREAD

**Issue by brysi73** [TomGrobbe/vMenu#76]
I don't know if many people care about this. But vMenu overrides the Heliscript (Essential to RP servers)
https://forum.fivem.net/t/release-heli-script/24094

I don't know what exactly is causing it but cannot thermal or NV or use spotlight.

This occurred when we added vMenu

**Comment by TomGrobbe** [comment]
What key binds are you using for nightvision and spotlight controls? and does this only happen when vMenu is opened, or even when it's closed?

**Comment by brysi73** [comment]
It occurred when it is closed and I am using the following keys I have tried with it open and closed

RIGHT MOUSE BUTTON - Thermal and Night Vision

and

G - to turn on the spotlight and it flashes shows up for a second and turns off

**Comment by TomGrobbe** [comment]
Interesting, because I never disable G in the first place in my menu. And right mouse button is only disabled when the menu is open so it shouldn't be possible to affect it. The only issue that I might have to look into is whether or not I loop enable/disable the night vision/thermal vision options in vMenu.

**Comment by TomGrobbe** [comment]
Night vision and thermal vision have been fixed. Though won't be released (properly) until the next _normal update_. Here is the dll file that you'll have to replace to fix the night/thermal vision issues:
[vMenuClient.net.zip](https://github.com/TomGrobbe/vMenu/files/1892172/vMenuClient.net.zip)
Note that this dll file supports v1.1.0 and up only, so upgrade to v1.1.0 first, then download this dll file, unzip it and replace it.

**Comment by TomGrobbe** [comment]
If you have more repro details for the spotlight issues then let me know but at this point there's nothing I can do because I'm not able to replicate the issue, it works fine for me.
