### ISSUE TITLE
set vMenuToggleMenuKey 168 will disable key F6

### ISSUE THREAD

**Issue by MatPain** [TomGrobbe/vMenu#87]
Hi Vespura,

i have a some trouble with i use the "set vMenuToggleMenuKey 168"

it will disable the key F6 from my other resource.

Did you need more information ?

Mat.

**Comment by TomGrobbe** [comment]
It disables it because when using the default key that would conflict on controller. So you’ll have to make your other resource compatible to use IsDisabledKeyJustReleased for example.

**Comment by MatPain** [comment]
thanks for your quickly answer

i tried to understand the native function but not working.

its to do like this ?

if IsControlJustPressed(1, 167) and IsDisabledKeyJustReleased(1, 168) then
....

**Comment by TomGrobbe** [comment]
no, like this:
```lua
if IsControlJustPressed(0, <control>) or IsDisabledControlJustPressed(0, <control>) then
```

**Comment by TomGrobbe** [comment]
_closed issue as it is not really an issue, but more of a problem with the other resource._
