### ISSUE TITLE
PVP not enabled. 

### ISSUE THREAD

**Issue by mbergwall2222** [TomGrobbe/vMenu#88]
When having this menu enabled on our servers, PVP is disabled. Is this an issue on our end or is there a menu option that disables this?

https://streamable.com/0wp32

**Comment by TomGrobbe** [comment]
This is probably because you just disabled scripthook and enabled this menu at the same time. Scripthook allows for pvp by default (when using a trainer), this menu does _not_ touch pvp at all, you'll need to get a resource that enables pvp. (for example, vBasic has an option to enable pvp)

**Comment by TomGrobbe** [comment]
maybe you have god mode enabled? Because my script never touches pvp...

**Comment by mbergwall2222** [comment]
Nope neither have god mode. I assume something else is messed up then. Appreciate it.

**Comment by TomGrobbe** [comment]
If you disable vMenu, does pvp turn back on?

**Comment by mbergwall2222** [comment]
Fixed it, we fixed our script lol
