### ISSUE TITLE
Weird Ped related vehicle spawning bug

### ISSUE THREAD

**Issue by matty45** [TomGrobbe/vMenu#90]
It seems that whenever a player spawns a vehicle, presumably with spawn inside vehicle checked, the player goes inside the vehicle but his ped stays out of it. It makes the vehicle look like it is being driven by a ghost.

**Comment by TomGrobbe** [comment]
what..... does this also happen if you disable all other resources? because 1) i've never had this myself, and 2) it hasn't happened to anyone else so far that i know of and 3) this is usually the cause of a session bugging out or too many resources trying to alter the player and a poor connection

**Comment by matty45** [comment]
I only have 7 resources running including vmenu.

**Comment by TomGrobbe** [comment]
>I have some steps to replicate. 
>Get another player on a server to do this
> 1. spawn a vehicle with spawn inside vehicle checked
> 2. drive around

Tried that already, no issues here on my end 😕

**Comment by matty45** [comment]
damn it, must be connection issue then
