### ISSUE TITLE
Unable to load connect - cannot load vMenu resource

### ISSUE THREAD

**Issue by ThatOctopus** [TomGrobbe/vMenu#93]
Just installed it on a fresh install of FiveM and when trying to load into the game with vMenu enabled i get the following. Host is a 16.04 Ubuntu Box. 

I have attached screenshots as my putty was acting up and wouldn't let me copy the information, if you need anymore information, i am happy to help.

![image](https://user-images.githubusercontent.com/17747034/40185409-758e5866-59ea-11e8-97a7-61deec2b2578.png)

![image](https://user-images.githubusercontent.com/17747034/40185462-91b37698-59ea-11e8-809b-f11c3806438a.png)
![image](https://user-images.githubusercontent.com/17747034/40185541-c07b8830-59ea-11e8-929e-2fc32ab177bb.png)
![image](https://user-images.githubusercontent.com/17747034/40185607-e10389cc-59ea-11e8-9e2e-e5208648d786.png)

**Comment by TomGrobbe** [comment]
If you clear your server cache once then restart your server twice, do you still get the same error? Also what version of vMenu are you using?

**Comment by ThatOctopus** [comment]
Clearing cache worked, cheers!


Sorry to waste time!



________________________________

**Comment by TomGrobbe** [comment]
Np, glad it works now.

**Comment by birkir0107** [comment]
TommGrobbe it does not work for me
