### ISSUE TITLE
Permissions won't work

### ISSUE THREAD

**Issue by csabike2** [TomGrobbe/vMenu#94]
Hey, thanks for this work!

One thing what won't work for me, is the permissions.
I've added all of the admins, but I want to disable the menu for the normal users.
If I leave the permissions unchanged, all of the normal users can open the vMenu and can make any server related changes like spawning vehicles.

If I modify the permissions (just the mods and the admins have access to the major menus - in config), it won't work either, normal player can open the menu, and spawn a car again.

What can I do with it?
Tried to disable everything, that work, even for the admins...

**Comment by TomGrobbe** [comment]
Have you read the wiki regarding removing permissions and also looking at wildcard permissions? Also, make sure to restart the server each time, only restarting the resource won’t work.

**Comment by csabike2** [comment]
Never mind, I've figured it out how to do it.
Basically removed everything except mod and admin features, and nothing has been set up for everyone, and now, its works.
