### ISSUE TITLE
vMenu reappears after closing any text box

### ISSUE THREAD

**Issue by jellyton69** [TomGrobbe/vMenu#95]
I have found that when a GTA text box is closed, vMenu pops up. Although it only happens after vMenu is initially opened at least once in that session.

http://zyriangaming.com/jelly/uploads/images/%5B%25t%5D%20May%2021%202018%20-%200646PM.gif
http://zyriangaming.com/jelly/uploads/images/%5B%25t%5D%20May%2021%202018%20-%200648PM.gif

**Comment by TomGrobbe** [comment]
What version of vMenu are you using? Because this was already fixed a long time ago....

**Comment by jellyton69** [comment]
Latest version: http://zyriangaming.com/jelly/uploads/images/%5Bmstsc%5D%20May%2022%202018%20-%2008-01PM%20053.png

**Comment by TomGrobbe** [comment]
So far, not been able to reproduce this consistently using lambda menu... Seems to happen very rarely...

**Comment by neos7** [comment]
It always happen even with my handling_editor script, seems that `DisplayOnscreenKeyboard` method triggers the vMenu to open somehow

**Comment by TomGrobbe** [comment]
It’s odd because it shouldn’t ever happen since the functionality was changed a long time ago...

**Comment by TomGrobbe** [comment]
Will have to look at it next week whenever I’ve got time

**Comment by Stealth22PD** [comment]
We ran into this...its kludgey, but basically, we added a bool that we set to true if vMenu opened the onscreen prompt.

Let me know if you want a code snippet.

**Comment by TomGrobbe** [comment]
It should be already done that way, unless I somehow broke the commit and never saved it... which seems unlikely but could be the case. I'll have a look.
