### ISSUE TITLE
Addon police cars

### ISSUE THREAD

**Issue by nkidwell1259** [TomGrobbe/vMenu#96]
I added the cars to the addon.json but the menu still shows as locked and the addon cars dont spawn by name. Just puts the standard gta v car is.

**Comment by TomGrobbe** [comment]
Then you haven't added the addon cars (correctly) to your server. If the model is not available, it will be locked. Not a vMenu issue in that case. Are you able to spawn them using another resource/trainer?

**Comment by nkidwell1259** [comment]
Yes we can with mello trainer. But we hate mello and are hoping to get this
to work. We are also using els+

**Comment by TomGrobbe** [comment]
The models must have something broken because vMenu checks if the model is available, if it isn't you won't be able to spawn it... Can you send me your addons file?

**Comment by nkidwell1259** [comment]
https://drive.google.com/file/d/1VU5qyuL8OWF1jaKoAeXbSmfQcuzC6Ntz/view?usp=drivesdk

**Comment by TomGrobbe** [comment]
I can't download that rar file, it's corrupted... And I actually meant your addons.json file instead 😉

**Comment by nkidwell1259** [comment]
I just went and looked. Those are actually replace police cars. So when we
installed the cars and els+ it all worked. Then we took out mello trainer
and added vmenu and that's when it stopped working. Is there something
different we have to do? Also for the addon.json I just changed the names
in the file to police and police2

**Comment by TomGrobbe** [comment]
Did you give yourself permissions to spawn police and police2? (access to the emergency category)

**Comment by nkidwell1259** [comment]
As far as I saw yes as it spawned the regular gta v police cars

**Comment by TomGrobbe** [comment]
>Then we took out mello trainer and added vmenu and that's when it stopped working

That can't be the only thing you've done, because vMenu does not alter any "models" itself whatsoever. Unless mello trainer streamed those vehicles, then it can't be something caused by vMenu... If you switch back to mello trainer, does it suddenly start working again?

**Comment by TomGrobbe** [comment]
Closed because the OP doesn't reply.
