### ISSUE TITLE
not able to remove unlimited stamina

### ISSUE THREAD

**Issue by Jhudri** [TomGrobbe/vMenu#97]
cant remove unlimited stamina to the everyone permission. I would like for people to be able to use the emotes but not be able to make them self's super human marathon runners.

**Comment by TomGrobbe** [comment]
@Jhudri What's the issue exactly? Because you can just setup the permissions according to the wiki and it will work fine.

**Comment by Jhudri** [comment]
@TomGrobbe im setting up permission's for player options to just use the emotes, but the issue is I cant disable the unlimited stamina toggle to the "everyone" permission. I can disable the menu but then "everyone"cant access the  emotes.

**Comment by TomGrobbe** [comment]
that's odd... i'll have a look in a little bit.

**Comment by TomGrobbe** [comment]
You're right it doesn't work. I'll have to look into this later, thanks for reporting it ;)

**Comment by Jhudri** [comment]
this is the permission list I'm using and I cant seem to find the # Player Options "unlimited stamina" to disable it. unless its made but not posted or maybe I just looked past it, I'm not sure. 



# Player Options
add_ace builtin.everyone "vMenu.PlayerOptions.Menu" allow
add_ace group.admin "vMenu.PlayerOptions.Menu" allow
add_ace group.admin "vMenu.PlayerOptions.All" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.God" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.Invisible" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.FastRun" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.FastSwim" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.Superjump" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.NoRagdoll" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.NeverWanted" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.SetWanted" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.Ignored" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.Functions" allow
#add_ace builtin.everyone "vMenu.PlayerOptions.Freeze" allow
add_ace builtin.everyone "vMenu.PlayerOptions.Scenarios" allow

**Comment by TomGrobbe** [comment]
Yeah, i tried it and it's broken, not sure what the issue is, will have to look into the code tomorrow.

**Comment by TomGrobbe** [comment]
I've just checked, and there was a reason why I didn't add a permission node for that feature specifically. According to the readme file, this was why:

>*(Some features do not have permissions support as they are either harmless or it'd just be silly to deny them. However, they will be disabled if you deny access to the submenu that they are a part of (eg: unlimited stamina in Player Options will be disabled if you deny `vMenu.PlayerOptions.Menu`.))

Though I think I may add it in the future.

**Comment by Jhudri** [comment]
It would really be  appreciated as unlimited  stamina in a rp server kinda brakes rp. I could disable the player option menu and us a different  resource but it would really be nice to have everything in one menu. Besides this issue this is by far one of the best out of the box, no hassle resources out there .

**Comment by TomGrobbe** [comment]
@Jhudri Yeah, though in my opinion, dying because you run 3 seconds and your stamina has run out, isn’t nice on any sever. Not something anyone would want, not even on a “realistic rp” server.

**Comment by TomGrobbe** [comment]
Just added permissions support for it in #00b50482af5db90dee014d77ab0ad5273d9c90c3 will be pushed to production in the next update.
