### ISSUE TITLE
vMenu only showing two options 

### ISSUE THREAD

**Issue by Matt4499** [TomGrobbe/vMenu#98]
When I open vMenu I only see two options. "Misc Settings" and "About vMenu"

I have "exec permissions.cfg" at the VERY top of server.cfg
Resource is named "vMenu" case sensitive

[permissions.txt](https://github.com/TomGrobbe/vMenu/files/2070895/permissions.txt)
My permissions file is attached. I only named it to .txt to upload it, it IS a .cfg on the server

I added my steam identifier (it is correct steam identifier) to group admin as you can see, I have deleted cache and restarted server several times. 

Running newest version of vMenu v1.1.4

I have also tried downloading and installing a fresh copy, didn't work. 

I have read the wiki and found nothing on this topic.

**Comment by TomGrobbe** [comment]
@Matt4499 Can you send me a server log from when you start the server and then join it, enable both client and server debug logging in the resource.lua. Also the client log would help

**Comment by Matt4499** [comment]
I enabled debug logging and then it magically worked. I feel like a complete idiot. Sorry about this. Still want logs?

**Comment by TomGrobbe** [comment]
@Matt4499 Well I would still like those logs if possible. Also I recommend turning logging back off as it can get really annoying for the user.

**Comment by TomGrobbe** [comment]
@TomGrobbe Though glad it works 😀

**Comment by Matt4499** [comment]
[CitizenFX.log](https://github.com/TomGrobbe/vMenu/files/2070922/CitizenFX.log)
server log
[CitizenFX.log](https://github.com/TomGrobbe/vMenu/files/2070926/CitizenFX.log)
client log

also while i've got you attention, is it possible to have "default" settings, like have voice range default to 5m?

**Comment by TomGrobbe** [comment]
Nope that’s not possible because it is set as a user preference. So it can’t be overridden by the server owner. If you want your users to use a default of 5, tell them to switch to 5, then hit save preferences in the misc settings menu.

**Comment by Matt4499** [comment]
Okay. Thank you for helping me!
