### ISSUE TITLE
New MK2 weapons dont seem to have any ammo type components.

### ISSUE THREAD

**Issue by matty45** [TomGrobbe/vMenu#99]
For some reason the old mk2 weapons have the ammo types just like this one:
![image](https://i.imgur.com/Vuju1HP.png)

However if you are using a new mk2 weapon like the mk2 special carbine:
![image](https://i.imgur.com/Q8aqJTp.png)

Is this problem related to a mistake on my end or something else?

**Comment by TomGrobbe** [comment]
I never added new components because I couldn’t find a list for the new ones. So I only added the model names for the new dlc weapons itself. If you have a list of _this dlc specific_ component hashes/names then let me know and I’ll add them.

**Comment by matty45** [comment]
https://notepad.pw/share/hksbla9

**Comment by TomGrobbe** [comment]
> https://notepad.pw/share/hksbla9

not the kind of list i was hoping for, but it'll do. Will take time to parse all that and implement the missing ones though.

**Comment by matty45** [comment]
Thanks!
